import type { Version } from "../../../../types/Scripture"

export const versions: Version[] = [
  {
    id: "0c2ff0a5c8b9069c-01",
    dblId: "0c2ff0a5c8b9069c",
    relatedDbl: null,
    name: "Nend Portions - Mark",
    nameLocal: "MAK Yakŋ Ohɨrand Ya Imbɨr Makɨv Mpamar",
    abbreviation: "NendNP03",
    abbreviationLocal: "NendNP03",
    description: null,
    descriptionLocal: "Mark in Nend",
    language: { id: "anh", name: "Nend", nameLocal: "Nend", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2021-06-08T14:40:00.000Z",
    audioBibles: [],
  },
  {
    id: "b17e246951402e50-01",
    dblId: "b17e246951402e50",
    relatedDbl: null,
    name: "Biblica® Open New Arabic Version 2012",
    nameLocal: "كتاب الحياة مجانى",
    abbreviation: "ONAV",
    abbreviationLocal: "KEHM",
    description: "Holy Bible",
    descriptionLocal: "ا‫لكتاب المقدس",
    language: { id: "arb", name: "Arabic, Standard", nameLocal: "العربية", script: "Arabic", scriptDirection: "RTL" },
    countries: [
      { id: "EG", name: "Egypt", nameLocal: "Egypt" },
      { id: "SA", name: "Saudi Arabia", nameLocal: "Saudi Arabia" },
    ],
    type: "text",
    updatedAt: "2021-09-30T09:11:27.000Z",
    audioBibles: [
      {
        id: "26b7a1cd2f8f4878-01",
        name: "Biblica® Open New Arabic Version 2012, Audio Edition",
        nameLocal: "Ketab El Hayat Majani/كتاب الحياة مجانى",
        dblId: "26b7a1cd2f8f4878",
      },
    ],
  },
  {
    id: "b7ad344da9c39262-01",
    dblId: "b7ad344da9c39262",
    relatedDbl: null,
    name: "Arapaho Luke",
    nameLocal: "Hethadenee waunauyaunee vadan Luke Vanenāna",
    abbreviation: "arp",
    abbreviationLocal: "arp",
    description: "common",
    descriptionLocal: "common",
    language: { id: "arp", name: "Arapaho", nameLocal: "Arapaho", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States", nameLocal: "United States" }],
    type: "text",
    updatedAt: "2020-09-15T05:31:49.000Z",
    audioBibles: [],
  },
  {
    id: "d199679f805f5b29-01",
    dblId: "d199679f805f5b29",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Assamese - 2019",
    nameLocal: "ইণ্ডিয়ান ৰিভাইচ ভাৰচন (IRV) আচামিচ - 2019",
    abbreviation: "IRVAsm",
    abbreviationLocal: "IRVAsm",
    description: "Indian Revised Version Holy Bible in the Assameese language of India",
    descriptionLocal: "Indian Revised Version Holy Bible in the Assameese language of India",
    language: { id: "asm", name: "Assamese", nameLocal: "অসমীয়া", script: "Bengali", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-29T00:34:59.000Z",
    audioBibles: [],
  },
  {
    id: "17c44f6c89de00db-01",
    dblId: "17c44f6c89de00db",
    relatedDbl: null,
    name: "Belarusian New Testament and Books of Old Testament",
    nameLocal: "Новы Запавет і Кнігі Старога Запавету",
    abbreviation: "NTPrv",
    abbreviationLocal: "НЗПрп",
    description: "Belarusian New Testament and Books of Old Testament",
    descriptionLocal: "Новы Запавет і Кнігі Старога Запавету",
    language: { id: "bel", name: "Belarusan", nameLocal: "беларуская", script: "Cyrillic", scriptDirection: "LTR" },
    countries: [{ id: "BY", name: "Belarus", nameLocal: "Belarus" }],
    type: "text",
    updatedAt: "2021-02-08T21:08:27.000Z",
    audioBibles: [],
  },
  {
    id: "b52bc8b7af3bdc6f-03",
    dblId: "b52bc8b7af3bdc6f",
    relatedDbl: null,
    name: "Bible (V. Semukha translation)",
    nameLocal: "Біблія (пераклад В. Сёмухі)",
    abbreviation: "BBL",
    abbreviationLocal: "ББЛ",
    description: "Synodal",
    descriptionLocal: "Сінадальны",
    language: { id: "bel", name: "Belarusian", nameLocal: "беларуская", script: "Cyrillic", scriptDirection: "LTR" },
    countries: [{ id: "BY", name: "Belarus", nameLocal: "Belarus" }],
    type: "text",
    updatedAt: "2020-09-15T05:29:51.000Z",
    audioBibles: [],
  },
  {
    id: "4c3eda00cd317568-01",
    dblId: "4c3eda00cd317568",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Bengali",
    nameLocal: "ইন্ডিয়ান রিভাইজড ভার্সন (IRV) - বেঙ্গলী",
    abbreviation: "IRVBen",
    abbreviationLocal: "IRVBen",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "ben", name: "Bengali", nameLocal: "বাংলা", script: "Bengali", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T19:22:40.000Z",
    audioBibles: [],
  },
  {
    id: "55bab459b716348c-01",
    dblId: "55bab459b716348c",
    relatedDbl: null,
    name: "Bedamuni Bible",
    nameLocal: "GODE EA SIA: IDA:IWANE GALA",
    abbreviation: "beo",
    abbreviationLocal: "BEO",
    description: "common",
    descriptionLocal: "common",
    language: { id: "beo", name: "Beami", nameLocal: "Beami", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T20:01:31.000Z",
    audioBibles: [],
  },
  {
    id: "6855dabfcb711cc2-01",
    dblId: "6855dabfcb711cc2",
    relatedDbl: null,
    name: "Blackfoot Matthew",
    nameLocal: "ŎKHS' I TSĬN IK SĬN NI ST. MATTHEW OT SĬN AI PI.",
    abbreviation: "bla1890",
    abbreviationLocal: "bla1890",
    description: "common",
    descriptionLocal: "common",
    language: { id: "bla", name: "Siksika", nameLocal: "Siksika", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "CA", name: "Canada", nameLocal: "Canada" }],
    type: "text",
    updatedAt: "2020-09-11T20:58:19.000Z",
    audioBibles: [],
  },
  {
    id: "71d2075d284c4eae-01",
    dblId: "71d2075d284c4eae",
    relatedDbl: null,
    name: "God's Holy Book",
    nameLocal: "Kitabu ka Kanu",
    abbreviation: "Baga",
    abbreviationLocal: "KKK",
    description: "The Law books, Psalms, the Gospel and the Letters of the Apostles",
    descriptionLocal: "Tawureta, Yabura, Iŋyila, kɔ reka ya asɔm a Yesu",
    language: { id: "bsp", name: "Baga Sitemu", nameLocal: "Baga Sitemu", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T21:26:40.000Z",
    audioBibles: [],
  },
  {
    id: "c61908161b077c4c-01",
    dblId: "c61908161b077c4c",
    relatedDbl: null,
    name: "Czech Kralická Bible 1613",
    nameLocal: "Bible Kralická 1613",
    abbreviation: "ces1613",
    abbreviationLocal: "BKR",
    description: "common",
    descriptionLocal: "společný",
    language: { id: "ces", name: "Czech", nameLocal: "Čeština", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "CZ", name: "Czech Republic", nameLocal: "Czech Republic" }],
    type: "text",
    updatedAt: "2020-09-12T00:19:28.000Z",
    audioBibles: [],
  },
  {
    id: "9ab28a81b9c4587d-01",
    dblId: "9ab28a81b9c4587d",
    relatedDbl: null,
    name: "Biblica® Open Kurdi Sorani Standard Version 2020",
    nameLocal: "ببلیکا – وەشانی بێبەرامبەری کوردیی سۆرانیی ستاندەر",
    abbreviation: "OKSS",
    abbreviationLocal: "OKSS",
    description: "Protestant Bible",
    descriptionLocal: "كتێبی پیرۆز",
    language: { id: "ckb", name: "Kurdish, Central", nameLocal: "كوردی سۆرانی", script: "Arabic", scriptDirection: "RTL" },
    countries: [{ id: "IQ", name: "Iraq", nameLocal: "Iraq" }],
    type: "text",
    updatedAt: "2021-05-01T09:11:23.000Z",
    audioBibles: [],
  },
  {
    id: "dca01eb41e39d25d-02",
    dblId: "dca01eb41e39d25d",
    relatedDbl: null,
    name: "Kwere Bible",
    nameLocal: "Biblia Ching'hwele",
    abbreviation: "Kwere",
    abbreviationLocal: "Kwere",
    description: "NT & Pentateuch",
    descriptionLocal: "NT & Pentateuch",
    language: { id: "cwe", name: "Kwere", nameLocal: "Kwere", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2020-07-29T01:17:23.000Z",
    audioBibles: [],
  },
  {
    id: "dca01eb41e39d25d-01",
    dblId: "dca01eb41e39d25d",
    relatedDbl: null,
    name: "The New Testament in Kwere",
    nameLocal: "Lagano da Sambi kwa Wanhu Wose",
    abbreviation: "Kwere",
    abbreviationLocal: "Kwere",
    description: "New Testament",
    descriptionLocal: "Kwere",
    language: { id: "cwe", name: "Kwere", nameLocal: "Kwere", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2020-07-29T01:17:10.000Z",
    audioBibles: [],
  },
  {
    id: "f492a38d0e52db0f-01",
    dblId: "f492a38d0e52db0f",
    relatedDbl: null,
    name: "Elberfelder Translation (Version of bibelkommentare.de)",
    nameLocal: "Elberfelder Übersetzung (Version von bibelkommentare.de)",
    abbreviation: "ELBBK",
    abbreviationLocal: "ELBBK",
    description: null,
    descriptionLocal: "Sprachlich aufgearbeiteter Text der unrevidierten Elberfelder Übersetzung mit Fußnoten.",
    language: { id: "deu", name: "German", nameLocal: "Deutsch", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "DE", name: "Germany", nameLocal: "Germany" }],
    type: "text",
    updatedAt: "2020-09-09T21:26:01.000Z",
    audioBibles: [],
  },
  {
    id: "926aa5efbc5e04e2-01",
    dblId: "926aa5efbc5e04e2",
    relatedDbl: null,
    name: "German Luther Bible 1912 with Strong's numbers",
    nameLocal: "Lutherbibel 1912 mit Strongs",
    abbreviation: "deuL1912",
    abbreviationLocal: "L1912",
    description: "Protestant",
    descriptionLocal: "Evangelisch",
    language: { id: "deu", name: "German, Standard", nameLocal: "Deutsch", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "DE", name: "Germany", nameLocal: "Germany" },
      { id: "AT", name: "Austria", nameLocal: "Austria" },
      { id: "CH", name: "Switzerland", nameLocal: "Switzerland" },
    ],
    type: "text",
    updatedAt: "2021-08-31T17:11:41.000Z",
    audioBibles: [],
  },
  {
    id: "95410db44ef800c1-01",
    dblId: "95410db44ef800c1",
    relatedDbl: null,
    name: "German Unrevised Elberfelder Bible",
    nameLocal: "Darby Unrevidierte Elberfelder",
    abbreviation: "deuelo",
    abbreviationLocal: "ELO",
    description: "Protestant",
    descriptionLocal: "evangelisch",
    language: { id: "deu", name: "German, Standard", nameLocal: "Deutsch", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "DE", name: "Germany", nameLocal: "Germany" },
      { id: "AT", name: "Austria", nameLocal: "Austria" },
    ],
    type: "text",
    updatedAt: "2021-01-20T09:10:28.000Z",
    audioBibles: [],
  },
  {
    id: "542b32484b6e38c2-01",
    dblId: "542b32484b6e38c2",
    relatedDbl: null,
    name: "The Holy Bible in German, translation by Kautzsch und Weizsäcker 1906",
    nameLocal: "Textbibel von Kautzsch und Weizsäcker",
    abbreviation: "deutkw",
    abbreviationLocal: "TKW",
    description: "common",
    descriptionLocal: "verbreitet",
    language: { id: "deu", name: "German", nameLocal: "Deutsch", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "DE", name: "Germany", nameLocal: "Germany" }],
    type: "text",
    updatedAt: "2020-09-11T19:50:00.000Z",
    audioBibles: [],
  },
  {
    id: "e578524a0893c6b7-01",
    dblId: "e578524a0893c6b7",
    relatedDbl: null,
    name: "Dawro New Testament",
    nameLocal: "Dawro New Testament",
    abbreviation: "DWNT",
    abbreviationLocal: "DWNT",
    description: "New Testament",
    descriptionLocal: "New Testament",
    language: { id: "dwr", name: "Dawro", nameLocal: "Dawro", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "ET", name: "Ethiopia", nameLocal: "Ethiopia" }],
    type: "text",
    updatedAt: "2020-07-29T02:05:27.000Z",
    audioBibles: [],
  },
  {
    id: "685d1470fe4d5c3b-01",
    dblId: "685d1470fe4d5c3b",
    relatedDbl: null,
    name: "American Standard Version (Byzantine Text with Apocrypha)",
    nameLocal: "American Standard Version Byzantine Text with Apocrypha",
    abbreviation: "ASVBT",
    abbreviationLocal: "ASVBT",
    description: null,
    descriptionLocal: null,
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-05-18T09:09:48.000Z",
    audioBibles: [],
  },
  {
    id: "bba9f40183526463-01",
    dblId: "bba9f40183526463",
    relatedDbl: null,
    name: "Berean Study Bible",
    nameLocal: "English: Berean Study Bible",
    abbreviation: "BSB",
    abbreviationLocal: "BSB",
    description: "Berean Study Bible",
    descriptionLocal: "English: Berean Study Bible",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "US", name: "United States of America", nameLocal: "United States of America" },
      { id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" },
      { id: "AU", name: "Australia", nameLocal: "Australia" },
      { id: "CA", name: "Canada", nameLocal: "Canada" },
      { id: "AG", name: "Antigua and Barbuda", nameLocal: "Antigua and Barbuda" },
      { id: "BS", name: "Bahamas", nameLocal: "Bahamas" },
      { id: "BB", name: "Barbados", nameLocal: "Barbados" },
      { id: "BZ", name: "Belize", nameLocal: "Belize" },
      { id: "DM", name: "Dominica", nameLocal: "Dominica" },
      { id: "DO", name: "Dominican Republic", nameLocal: "Dominican Republic" },
      { id: "AS", name: "American Samoa", nameLocal: "American Samoa" },
      { id: "GU", name: "Guam", nameLocal: "Guam" },
      { id: "HT", name: "Haiti", nameLocal: "Haiti" },
      { id: "GY", name: "Guyana", nameLocal: "Guyana" },
      { id: "IL", name: "Israel", nameLocal: "Israel" },
      { id: "IE", name: "Ireland", nameLocal: "Ireland" },
      { id: "JM", name: "Jamaica", nameLocal: "Jamaica" },
      { id: "MT", name: "Malta", nameLocal: "Malta" },
      { id: "NZ", name: "New Zealand", nameLocal: "New Zealand" },
      { id: "PH", name: "Philippines", nameLocal: "Philippines" },
      { id: "KN", name: "Saint Kitts and Nevis", nameLocal: "Saint Kitts and Nevis" },
      { id: "LC", name: "Saint Lucia", nameLocal: "Saint Lucia" },
      { id: "VC", name: "Saint Vincent and the Grenadines", nameLocal: "Saint Vincent and the Grenadines" },
      { id: "TT", name: "Trinidad and Tobago", nameLocal: "Trinidad and Tobago" },
      { id: "NG", name: "Nigeria", nameLocal: "Nigeria" },
      { id: "ZA", name: "South Africa", nameLocal: "South Africa" },
    ],
    type: "text",
    updatedAt: "2021-07-14T21:11:53.000Z",
    audioBibles: [],
  },
  {
    id: "6bab4d6c61b31b80-01",
    dblId: "6bab4d6c61b31b80",
    relatedDbl: null,
    name: "Brenton English Septuagint (Updated Spelling and Formatting)",
    nameLocal: "Brenton English Septuagint (Updated Spelling and Formatting)",
    abbreviation: "engLXXup",
    abbreviationLocal: "LXXup",
    description: "common",
    descriptionLocal: "common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "ZZ", name: "Unspecific", nameLocal: "Unspecific" }],
    type: "text",
    updatedAt: "2020-07-28T15:54:25.000Z",
    audioBibles: [],
  },
  {
    id: "65bfdebd704a8324-01",
    dblId: "65bfdebd704a8324",
    relatedDbl: null,
    name: "Brenton English translation of the Septuagint",
    nameLocal: "Brenton English translation of the Septuagint",
    abbreviation: "engbrent",
    abbreviationLocal: "Brenton",
    description: "Septuagint",
    descriptionLocal: "Septuagint",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "GB", name: "United Kingdom", nameLocal: "United Kingdom" },
      { id: "US", name: "United States", nameLocal: "United States" },
    ],
    type: "text",
    updatedAt: "2020-09-11T20:50:20.000Z",
    audioBibles: [],
  },
  {
    id: "55212e3cf5d04d49-01",
    dblId: "55212e3cf5d04d49",
    relatedDbl: null,
    name: "Cambridge Paragraph Bible of the KJV",
    nameLocal: "Cambridge Paragraph Bible of the KJV",
    abbreviation: "engKJVCPB",
    abbreviationLocal: "KJVCPB",
    description: "Common",
    descriptionLocal: "Common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States", nameLocal: "United States" }],
    type: "text",
    updatedAt: "2020-09-09T21:52:35.000Z",
    audioBibles: [],
  },
  {
    id: "179568874c45066f-01",
    dblId: "179568874c45066f",
    relatedDbl: null,
    name: "Douay-Rheims American 1899",
    nameLocal: "Douay-Rheims American 1899",
    abbreviation: "engDRA",
    abbreviationLocal: "DRA",
    description: "The Holy Bible in English, Douay-Rheims American Edition of 1899, translated from the Latin Vulgate",
    descriptionLocal: "Catholic",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States", nameLocal: "United States" }],
    type: "text",
    updatedAt: "2020-10-12T20:18:43.000Z",
    audioBibles: [],
  },
  {
    id: "55ec700d9e0d77ea-01",
    dblId: "55ec700d9e0d77ea",
    relatedDbl: null,
    name: "English Majority Text Version",
    nameLocal: "English Majority Text Version",
    abbreviation: "engEMTV",
    abbreviationLocal: "EMTV",
    description: "common",
    descriptionLocal: "common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States", nameLocal: "United States" }],
    type: "text",
    updatedAt: "2020-09-11T20:03:01.000Z",
    audioBibles: [],
  },
  {
    id: "65eec8e0b60e656b-01",
    dblId: "65eec8e0b60e656b",
    relatedDbl: null,
    name: "Free Bible Version",
    nameLocal: "Free Bible Version",
    abbreviation: "FBV",
    abbreviationLocal: "FBV",
    description: "Protestant FBV full 3.0 beta",
    descriptionLocal: "Protestant FBV full 3.0 beta",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States", nameLocal: "United States" }],
    type: "text",
    updatedAt: "2021-01-22T09:10:23.000Z",
    audioBibles: [],
  },
  {
    id: "c315fa9f71d4af3a-01",
    dblId: "c315fa9f71d4af3a",
    relatedDbl: null,
    name: "Geneva Bible",
    nameLocal: "Geneva Bible",
    abbreviation: "enggnv",
    abbreviationLocal: "GNV",
    description: "common",
    descriptionLocal: "common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom", nameLocal: "United Kingdom" }],
    type: "text",
    updatedAt: "2020-09-15T05:45:48.000Z",
    audioBibles: [],
  },
  {
    id: "bf8f1c7f3f9045a5-01",
    dblId: "bf8f1c7f3f9045a5",
    relatedDbl: null,
    name: "JPS TaNaKH 1917",
    nameLocal: "JPS TaNaKH 1917",
    abbreviation: "engojps",
    abbreviationLocal: "OJPS",
    description: "Jewish",
    descriptionLocal: "Jewish",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States", nameLocal: "United States" }],
    type: "text",
    updatedAt: "2020-07-28T23:12:45.000Z",
    audioBibles: [],
  },
  {
    id: "de4e12af7f28f599-01",
    dblId: "de4e12af7f28f599",
    relatedDbl: null,
    name: "King James (Authorised) Version",
    nameLocal: "King James Version",
    abbreviation: "engKJV",
    abbreviationLocal: "KJV",
    description: "Ecumenical",
    descriptionLocal: "Ecumenical",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom", nameLocal: "United Kingdom" }],
    type: "text",
    updatedAt: "2020-11-12T21:16:24.000Z",
    audioBibles: [],
  },
  {
    id: "de4e12af7f28f599-02",
    dblId: "de4e12af7f28f599",
    relatedDbl: null,
    name: "King James (Authorised) Version",
    nameLocal: "King James Version",
    abbreviation: "engKJV",
    abbreviationLocal: "KJV",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom", nameLocal: "United Kingdom" }],
    type: "text",
    updatedAt: "2020-11-12T21:16:55.000Z",
    audioBibles: [],
  },
  {
    id: "01b29f4b342acc35-01",
    dblId: "01b29f4b342acc35",
    relatedDbl: null,
    name: "Literal Standard Version",
    nameLocal: "Literal Standard Version",
    abbreviation: "LSV",
    abbreviationLocal: "LSV",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "US", name: "United States", nameLocal: "United States" },
      { id: "GB", name: "United Kingdom", nameLocal: "United Kingdom" },
      { id: "CA", name: "Canada", nameLocal: "Canada" },
      { id: "AU", name: "Australia", nameLocal: "Australia" },
      { id: "ZA", name: "South Africa", nameLocal: "South Africa" },
      { id: "NZ", name: "New Zealand", nameLocal: "New Zealand" },
    ],
    type: "text",
    updatedAt: "2021-09-17T09:11:20.000Z",
    audioBibles: [],
  },
  {
    id: "40072c4a5aba4022-01",
    dblId: "40072c4a5aba4022",
    relatedDbl: null,
    name: "Revised Version 1885",
    nameLocal: "Revised Version 1885",
    abbreviation: "engRV",
    abbreviationLocal: "RV",
    description: "Interconfessional",
    descriptionLocal: "Interconfessional",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" }],
    type: "text",
    updatedAt: "2021-11-15T21:15:46.000Z",
    audioBibles: [],
  },
  {
    id: "ec290b5045ff54a5-01",
    dblId: "ec290b5045ff54a5",
    relatedDbl: null,
    name: "Targum Onkelos Etheridge",
    nameLocal: "Targum Onkelos Etheridge",
    abbreviation: "engOKE",
    abbreviationLocal: "OKE",
    description: "common",
    descriptionLocal: "common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "ZZ", name: "Unspecific", nameLocal: "Unspecific" }],
    type: "text",
    updatedAt: "2020-07-29T02:31:40.000Z",
    audioBibles: [],
  },
  {
    id: "2f0fd81d7b85b923-01",
    dblId: "2f0fd81d7b85b923",
    relatedDbl: null,
    name: "The English New Testament According to Family 35",
    nameLocal: "The English New Testament According to Family 35",
    abbreviation: "engF35",
    abbreviationLocal: "F35",
    description: "Common",
    descriptionLocal: "Common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "ZZ", name: "Unspecific", nameLocal: "Unspecific" }],
    type: "text",
    updatedAt: "2020-09-09T21:52:33.000Z",
    audioBibles: [],
  },
  {
    id: "06125adad2d5898a-01",
    dblId: "06125adad2d5898a",
    relatedDbl: null,
    name: "The Holy Bible, American Standard Version",
    nameLocal: "The Holy Bible, American Standard Version",
    abbreviation: "ASV",
    abbreviationLocal: "ASV",
    description: "Bible",
    descriptionLocal: "Bible",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-01-22T09:07:29.000Z",
    audioBibles: [],
  },
  {
    id: "66c22495370cdfc0-01",
    dblId: "66c22495370cdfc0",
    relatedDbl: null,
    name: "Translation for Translators",
    nameLocal: "Translation for Translators",
    abbreviation: "T4T",
    abbreviationLocal: "T4T",
    description: "common",
    descriptionLocal: "common",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-11-15T21:19:27.000Z",
    audioBibles: [],
  },
  {
    id: "9879dbb7cfe39e4d-01",
    dblId: "9879dbb7cfe39e4d",
    relatedDbl: null,
    name: "World English Bible",
    nameLocal: "World English Bible",
    abbreviation: "WEB",
    abbreviationLocal: "WEB",
    description: "Ecumenical",
    descriptionLocal: "Ecumenical",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-07-11T09:12:36.000Z",
    audioBibles: [
      {
        id: "105a06b6146d11e7-01",
        name: "English - World English Bible 2013 (Drama NT)",
        nameLocal: "English - World English Bible 2013 (Drama NT)",
        dblId: "105a06b6146d11e7",
      },
    ],
  },
  {
    id: "9879dbb7cfe39e4d-02",
    dblId: "9879dbb7cfe39e4d",
    relatedDbl: null,
    name: "World English Bible",
    nameLocal: "World English Bible",
    abbreviation: "WEB",
    abbreviationLocal: "WEB",
    description: "Catholic",
    descriptionLocal: "Catholic",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-07-11T09:13:10.000Z",
    audioBibles: [
      {
        id: "105a06b6146d11e7-01",
        name: "English - World English Bible 2013 (Drama NT)",
        nameLocal: "English - World English Bible 2013 (Drama NT)",
        dblId: "105a06b6146d11e7",
      },
    ],
  },
  {
    id: "9879dbb7cfe39e4d-03",
    dblId: "9879dbb7cfe39e4d",
    relatedDbl: null,
    name: "World English Bible",
    nameLocal: "World English Bible",
    abbreviation: "WEB",
    abbreviationLocal: "WEB",
    description: "Orthodox",
    descriptionLocal: "Orthodox",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-07-11T09:13:41.000Z",
    audioBibles: [
      {
        id: "105a06b6146d11e7-01",
        name: "English - World English Bible 2013 (Drama NT)",
        nameLocal: "English - World English Bible 2013 (Drama NT)",
        dblId: "105a06b6146d11e7",
      },
    ],
  },
  {
    id: "9879dbb7cfe39e4d-04",
    dblId: "9879dbb7cfe39e4d",
    relatedDbl: null,
    name: "World English Bible",
    nameLocal: "World English Bible",
    abbreviation: "WEB",
    abbreviationLocal: "WEB",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-07-11T09:14:16.000Z",
    audioBibles: [
      {
        id: "105a06b6146d11e7-01",
        name: "English - World English Bible 2013 (Drama NT)",
        nameLocal: "English - World English Bible 2013 (Drama NT)",
        dblId: "105a06b6146d11e7",
      },
    ],
  },
  {
    id: "7142879509583d59-01",
    dblId: "7142879509583d59",
    relatedDbl: null,
    name: "World English Bible British Edition",
    nameLocal: "World English Bible British Edition",
    abbreviation: "WEBBE",
    abbreviationLocal: "WEBBE",
    description: "Ecumenical",
    descriptionLocal: "Ecumenical",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" }],
    type: "text",
    updatedAt: "2021-07-11T09:10:05.000Z",
    audioBibles: [],
  },
  {
    id: "7142879509583d59-02",
    dblId: "7142879509583d59",
    relatedDbl: null,
    name: "World English Bible British Edition",
    nameLocal: "World English Bible British Edition",
    abbreviation: "WEBBE",
    abbreviationLocal: "WEBBE",
    description: "Catholic",
    descriptionLocal: "Catholic",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" }],
    type: "text",
    updatedAt: "2021-07-11T09:10:38.000Z",
    audioBibles: [],
  },
  {
    id: "7142879509583d59-03",
    dblId: "7142879509583d59",
    relatedDbl: null,
    name: "World English Bible British Edition",
    nameLocal: "World English Bible British Edition",
    abbreviation: "WEBBE",
    abbreviationLocal: "WEBBE",
    description: "Orthodox",
    descriptionLocal: "Orthodox",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" }],
    type: "text",
    updatedAt: "2021-07-11T09:11:12.000Z",
    audioBibles: [],
  },
  {
    id: "7142879509583d59-04",
    dblId: "7142879509583d59",
    relatedDbl: null,
    name: "World English Bible British Edition",
    nameLocal: "World English Bible British Edition",
    abbreviation: "WEBBE",
    abbreviationLocal: "WEBBE",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" }],
    type: "text",
    updatedAt: "2021-07-11T09:11:44.000Z",
    audioBibles: [],
  },
  {
    id: "f72b840c855f362c-04",
    dblId: "f72b840c855f362c",
    relatedDbl: null,
    name: "World Messianic Bible",
    nameLocal: "World Messianic Bible",
    abbreviation: "WMB",
    abbreviationLocal: "WMB",
    description: "Messianic",
    descriptionLocal: "Messianic",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "US", name: "United States of America", nameLocal: "United States of America" }],
    type: "text",
    updatedAt: "2021-09-15T21:59:35.000Z",
    audioBibles: [],
  },
  {
    id: "04da588535d2f823-04",
    dblId: "04da588535d2f823",
    relatedDbl: null,
    name: "World Messianic Bible British Edition",
    nameLocal: "World Messianic Bible British Edition",
    abbreviation: "WMBBE",
    abbreviationLocal: "WMBBE",
    description: "Messianic",
    descriptionLocal: "Messianic",
    language: { id: "eng", name: "English", nameLocal: "English", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "AU", name: "Australia", nameLocal: "Australia" },
      { id: "AS", name: "American Samoa", nameLocal: "American Samoa" },
      { id: "BS", name: "Bahamas", nameLocal: "Bahamas" },
      { id: "BZ", name: "Belize", nameLocal: "Belize" },
      { id: "IO", name: "British Indian Ocean Territory", nameLocal: "British Indian Ocean Territory" },
      { id: "VG", name: "Virgin Islands, British", nameLocal: "Virgin Islands, British" },
      { id: "CA", name: "Canada", nameLocal: "Canada" },
      { id: "KE", name: "Kenya", nameLocal: "Kenya" },
      { id: "FM", name: "Micronesia, Federated States of", nameLocal: "Micronesia, Federated States of" },
      { id: "NZ", name: "New Zealand", nameLocal: "New Zealand" },
      { id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" },
      { id: "WS", name: "Samoa", nameLocal: "Samoa" },
      { id: "SG", name: "Singapore", nameLocal: "Singapore" },
      { id: "TO", name: "Tonga", nameLocal: "Tonga" },
      { id: "GB", name: "United Kingdom of Great Britain and Northern Ireland", nameLocal: "United Kingdom of Great Britain and Northern Ireland" },
    ],
    type: "text",
    updatedAt: "2021-11-15T19:28:57.000Z",
    audioBibles: [],
  },
  {
    id: "9b076bc0f1856204-01",
    dblId: "9b076bc0f1856204",
    relatedDbl: null,
    name: "Pular Fuuta-Jallon Version",
    nameLocal: "Version Pular Fuuta-Jallon",
    abbreviation: "PFJV",
    abbreviationLocal: "VPFJ",
    description: "New Testament",
    descriptionLocal: "Injil",
    language: { id: "fuf", name: "Pular", nameLocal: "Pular", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T23:37:26.000Z",
    audioBibles: [],
  },
  {
    id: "da905e46720432e2-01",
    dblId: "da905e46720432e2",
    relatedDbl: null,
    name: "New Testament in Mborena Kam",
    nameLocal: "Raraŋ Aetaniacna Kam Wembaŋ Laŋ",
    abbreviation: "MbKamNT",
    abbreviationLocal: "MbKamNT",
    description: "New Testament in Mbore language (Mborena Kam)",
    descriptionLocal: "NT Mborena Kam",
    language: { id: "gai", name: "Borei", nameLocal: "Mborena Kam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-12T00:37:17.000Z",
    audioBibles: [],
  },
  {
    id: "e8b818f49c7c2835-01",
    dblId: "e8b818f49c7c2835",
    relatedDbl: null,
    name: "The New Testament in Kire",
    nameLocal: "Fhe Bakɨmen Kaman Kameŋ",
    abbreviation: "KirNT",
    abbreviationLocal: "KirNT",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "geb", name: "Kire", nameLocal: "Kire", script: "Latin (Roman) with Papua New Guinea enhancements", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-07-29T02:15:12.000Z",
    audioBibles: [],
  },
  {
    id: "901dcd9744e1bf69-01",
    dblId: "901dcd9744e1bf69",
    relatedDbl: null,
    name: "1904 Patriarchal Greek New Testament with 20 corrections from later editions",
    nameLocal: "Βυζαντινή Καινή Διαθήκη 1904",
    abbreviation: "grcBYZ1904c",
    abbreviationLocal: "BYZ1904",
    description: "Common",
    descriptionLocal: "κοινός",
    language: { id: "grc", name: "Greek, Ancient", nameLocal: "Ελληνιστική", script: "Greek", scriptDirection: "LTR" },
    countries: [{ id: "GR", name: "Greece", nameLocal: "Greece" }],
    type: "text",
    updatedAt: "2021-05-25T09:11:19.000Z",
    audioBibles: [],
  },
  {
    id: "c114c33098c4fef1-01",
    dblId: "c114c33098c4fef1",
    relatedDbl: null,
    name: "Brenton Greek Septuagint",
    nameLocal: "μετάφραση των εβδομήκοντα",
    abbreviation: "grcbrent",
    abbreviationLocal: "GRCBRENT",
    description: "common",
    descriptionLocal: "κοινός",
    language: { id: "grc", name: "Greek, Ancient", nameLocal: "Ελληνιστική", script: "Greek", scriptDirection: "LTR" },
    countries: [{ id: "GR", name: "Greece", nameLocal: "Greece" }],
    type: "text",
    updatedAt: "2020-07-28T16:17:49.000Z",
    audioBibles: [],
  },
  {
    id: "3aefb10641485092-01",
    dblId: "3aefb10641485092",
    relatedDbl: null,
    name: "Greek Textus Receptus",
    nameLocal: "Η Καινή Διαθήκη",
    abbreviation: "GRCTR",
    abbreviationLocal: "GRCTR",
    description: "common",
    descriptionLocal: "κοινός",
    language: { id: "grc", name: "Greek, Ancient", nameLocal: "Ελληνιστική", script: "Greek", scriptDirection: "LTR" },
    countries: [{ id: "ZZ", name: "Unspecific", nameLocal: "Unspecific" }],
    type: "text",
    updatedAt: "2021-06-01T09:08:19.000Z",
    audioBibles: [],
  },
  {
    id: "5e29945cf530b0f6-01",
    dblId: "5e29945cf530b0f6",
    relatedDbl: null,
    name: "The Greek New Testament According to Family 35",
    nameLocal: "Η Ελληνική Καινή Διαθήκη Σύμφωνα με την Οικογένεια 35",
    abbreviation: "grcF35",
    abbreviationLocal: "F35",
    description: "common",
    descriptionLocal: "κοινός",
    language: { id: "grc", name: "Greek, Ancient", nameLocal: "Ελληνιστική", script: "Greek", scriptDirection: "LTR" },
    countries: [{ id: "ZZ", name: "Unspecific", nameLocal: "Unspecific" }],
    type: "text",
    updatedAt: "2020-09-09T21:53:51.000Z",
    audioBibles: [],
  },
  {
    id: "3548ab6114a312d4-02",
    dblId: "3548ab6114a312d4",
    relatedDbl: null,
    name: "Gujarati Bible",
    nameLocal: "ગુજરાતી બાઇબલ",
    abbreviation: "gujBCS",
    abbreviationLocal: "GUJBCS",
    description: "common",
    descriptionLocal: "common",
    language: { id: "guj", name: "Gujarati", nameLocal: "ગુજરાતી", script: "Gujarati", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T04:08:07.000Z",
    audioBibles: [],
  },
  {
    id: "3548ab6114a312d4-01",
    dblId: "3548ab6114a312d4",
    relatedDbl: null,
    name: "Gujarati New Testament",
    nameLocal: "ગુજરાતી બાઇબલ",
    abbreviation: "guj",
    abbreviationLocal: "GUJ",
    description: "common",
    descriptionLocal: "common",
    language: { id: "guj", name: "Gujarati", nameLocal: "ગુજરાતી", script: "Gujarati", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-06-05T16:07:53.000Z",
    audioBibles: [],
  },
  {
    id: "0ab0c764d56a715d-01",
    dblId: "0ab0c764d56a715d",
    relatedDbl: null,
    name: "Biblica® Open Hausa Contemporary Bible 2020",
    nameLocal: "Biblica® Buɗaɗɗen Littafi Mai Tsarki, Sabon Rai Don Kowa 2020",
    abbreviation: "BHCB",
    abbreviationLocal: "OSRK",
    description: "New Testament",
    descriptionLocal: "Sabon Alkawari",
    language: { id: "hau", name: "Hausa", nameLocal: "Hausa", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "NG", name: "Nigeria", nameLocal: "Nigeria" }],
    type: "text",
    updatedAt: "2021-04-23T09:07:20.000Z",
    audioBibles: [],
  },
  {
    id: "0ab0c764d56a715d-02",
    dblId: "0ab0c764d56a715d",
    relatedDbl: null,
    name: "Biblica® Open Hausa Contemporary Bible 2020",
    nameLocal: "Biblica® Buɗaɗɗen Littafi Mai Tsarki, Sabon Rai Don Kowa 2020",
    abbreviation: "OHCB",
    abbreviationLocal: "BSRK",
    description: "Holy Bible",
    descriptionLocal: "Littafi mai Tsarki",
    language: { id: "hau", name: "Hausa", nameLocal: "Hausa", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "NG", name: "Nigeria", nameLocal: "Nigeria" }],
    type: "text",
    updatedAt: "2021-04-23T09:07:33.000Z",
    audioBibles: [],
  },
  {
    id: "705aad6832c6e4d2-02",
    dblId: "705aad6832c6e4d2",
    relatedDbl: null,
    name: "The Holy Bible in Hindi",
    nameLocal: "पवित्र बाइबिल",
    abbreviation: "hinirv",
    abbreviationLocal: "HINIRV",
    description: "common",
    descriptionLocal: "common",
    language: { id: "hin", name: "Hindi", nameLocal: "हिन्दी", script: "Devanagari", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T21:21:11.000Z",
    audioBibles: [],
  },
  {
    id: "9dec3e0ffbd4386b-01",
    dblId: "9dec3e0ffbd4386b",
    relatedDbl: null,
    name: "The New Testament in Holiya Language",
    nameLocal: "परमेश्‍वर उन खरा वचन, व्‍हाशोद नियम",
    abbreviation: "NTHaa20",
    abbreviationLocal: "NTHaa20",
    description: "The New Testament in Holiya Language, 2020",
    descriptionLocal: "परमेश्‍वर उन खरा वचन, व्‍हाशोद नियम, 2020",
    language: { id: "hoy", name: "Holiya", nameLocal: "Holiya", script: "Devanagari", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-11-01T09:10:01.000Z",
    audioBibles: [],
  },
  {
    id: "2dd568eeff29fb3c-02",
    dblId: "2dd568eeff29fb3c",
    relatedDbl: null,
    name: "Plain Indonesian Translation",
    nameLocal: "Terjemahan Sederhana Indonesia",
    abbreviation: "TSI",
    abbreviationLocal: "TSi",
    description: "Easy to understand every day translation",
    descriptionLocal: "menikmati terjemahan Alkitab yang mudah dimengerti",
    language: { id: "ind", name: "Indonesian", nameLocal: "Indonesia, bahasa", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "ID", name: "Indonesia", nameLocal: "Indonesia" },
      { id: "MY", name: "Malaysia", nameLocal: "Malaysia" },
    ],
    type: "text",
    updatedAt: "2021-11-19T09:09:33.000Z",
    audioBibles: [],
  },
  {
    id: "2dd568eeff29fb3c-01",
    dblId: "2dd568eeff29fb3c",
    relatedDbl: null,
    name: "Terjemahan Sederhana Indonesia NT Second Edition",
    nameLocal: "Perjanjian Baru dalam Terjemahan Sederhana Indonesia Edisi Kedua",
    abbreviation: "TSI",
    abbreviationLocal: "TSI",
    description: "New Testament and some other books",
    descriptionLocal: "Perjanjian Baru dalam Terjemahan Sederhana Indonesia",
    language: { id: "ind", name: "Indonesian", nameLocal: "Indonesia, bahasa", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "ID", name: "Indonesia", nameLocal: "Indonesia" },
      { id: "MY", name: "Malaysia", nameLocal: "Malaysia" },
    ],
    type: "text",
    updatedAt: "2020-02-12T00:10:07.000Z",
    audioBibles: [],
  },
  {
    id: "41f25b97f468e10b-01",
    dblId: "41f25b97f468e10b",
    relatedDbl: null,
    name: "Diodati Bible 1885",
    nameLocal: "Diodati Bibbia 1885",
    abbreviation: "DB1885",
    abbreviationLocal: "DB1885",
    description: "Diodati Bible 1885",
    descriptionLocal: "Diodati Bibbia 1885",
    language: { id: "ita", name: "Italian", nameLocal: "Italiano", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IT", name: "Italy", nameLocal: "Italy" }],
    type: "text",
    updatedAt: "2020-09-15T04:20:52.000Z",
    audioBibles: [],
  },
  {
    id: "a33a100f04f2752e-01",
    dblId: "a33a100f04f2752e",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Kannada - 2019",
    nameLocal: "ಇಂಡಿಯನ್ ರಿವೈಜ್ಡ್ ವರ್ಸನ್ (IRV) - ಕನ್ನಡ - 2019",
    abbreviation: "IRVKan",
    abbreviationLocal: "IRVKan",
    description: "Bible for all",
    descriptionLocal: "Bible for all",
    language: { id: "kan", name: "Kannada", nameLocal: "ಕನ್ನಡ", script: "Kannada", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-28T20:42:47.000Z",
    audioBibles: [],
  },
  {
    id: "f2f349d77ac8f8bc-01",
    dblId: "f2f349d77ac8f8bc",
    relatedDbl: null,
    name: "The New Testament in Kutu",
    nameLocal: "Lagano da Sambi kwa Wanhu Wose",
    abbreviation: "Kutu",
    abbreviationLocal: "Kutu",
    description: "New Testament",
    descriptionLocal: "Kutu",
    language: { id: "kdc", name: "Kutu", nameLocal: "Kutu", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-07-29T02:56:41.000Z",
    audioBibles: [],
  },
  {
    id: "c11c93a0b8a04496-01",
    dblId: "c11c93a0b8a04496",
    relatedDbl: null,
    name: "Makonde NT",
    nameLocal: "Lilailano Lyahambi Lya Nnungu Kwa Vanu Vammalele",
    abbreviation: "Makonde",
    abbreviationLocal: "Makonde",
    description: "NT",
    descriptionLocal: "Makonde",
    language: { id: "kde", name: "Makonde", nameLocal: "Shimakonde", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2021-07-19T21:12:22.000Z",
    audioBibles: [],
  },
  {
    id: "f258cb39615c351d-01",
    dblId: "f258cb39615c351d",
    relatedDbl: null,
    name: "Kharam New Testament",
    nameLocal: "Bible Inzootna Kathar",
    abbreviation: "KHMNT",
    abbreviationLocal: "KHMNT",
    description: "Kharam New Testament 2021",
    descriptionLocal: "Bible Inzootna Kathar",
    language: { id: "kfw", name: "Naga, Kharam", nameLocal: "Naga, Kharam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2021-03-03T21:13:01.000Z",
    audioBibles: [],
  },
  {
    id: "be8dc4ba39edf911-01",
    dblId: "be8dc4ba39edf911",
    relatedDbl: null,
    name: "Biblica® Open Kikuyu Holy Word of God™",
    nameLocal: "Biblica® Kiugo Gĩtheru Kĩa Ngai Kĩhingũre™",
    abbreviation: "OKGN",
    abbreviationLocal: "KGNK",
    description: "Holy Bible in Gĩkũyũ",
    descriptionLocal: "Kiugo Gĩtheru Kĩa Ngai",
    language: { id: "kik", name: "Gikuyu", nameLocal: "Gikuyu", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "KE", name: "Kenya", nameLocal: "Kenya" }],
    type: "text",
    updatedAt: "2021-05-18T09:16:15.000Z",
    audioBibles: [],
  },
  {
    id: "df7d5d71526afe9e-01",
    dblId: "df7d5d71526afe9e",
    relatedDbl: null,
    name: "Kapingamarangi Bible",
    nameLocal: "Beebaa Dabu",
    abbreviation: "kpg",
    abbreviationLocal: "kpg",
    description: "Common",
    descriptionLocal: "Common",
    language: { id: "kpg", name: "Kapingamarangi", nameLocal: "Kapingamarangi", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "FM", name: "Micronesia", nameLocal: "Micronesia" }],
    type: "text",
    updatedAt: "2020-09-12T00:42:15.000Z",
    audioBibles: [],
  },
  {
    id: "5591cba5ae063228-01",
    dblId: "5591cba5ae063228",
    relatedDbl: null,
    name: "Mum Language NT Portions",
    nameLocal: "Mum Tok Ples",
    abbreviation: "MumNP18",
    abbreviationLocal: "MumNP18",
    description: "Mum Matthew",
    descriptionLocal: "Mum Matyu",
    language: { id: "kqa", name: "Mum", nameLocal: "Mum", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T20:00:06.000Z",
    audioBibles: [],
  },
  {
    id: "6aa52b968434d882-01",
    dblId: "6aa52b968434d882",
    relatedDbl: null,
    name: "The Book of Mark - Kianying Balang",
    nameLocal: "Mak - Kiañiŋ Balaŋ",
    abbreviation: "KBNT",
    abbreviationLocal: "KBNT",
    description: "Gospel of Mark",
    descriptionLocal: "Gutnius bilong Mak",
    language: { id: "kql", name: "Kyenele", nameLocal: "Kiañiŋ Balaŋ", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T22:10:47.000Z",
    audioBibles: [],
  },
  {
    id: "f276be3571f516cb-01",
    dblId: "f276be3571f516cb",
    relatedDbl: null,
    name: "Biblica® Open Luganda Contemporary Bible 2014",
    nameLocal: "Biblica® Bayibuli Entukuvu, Endagaano Enkadde nʼEndagaano Empya ekwatiddwa ku katambi™",
    abbreviation: "OLCB",
    abbreviationLocal: "EEEE",
    description: "The Holy Bible",
    descriptionLocal: "Bayibuli Entukuvu",
    language: { id: "lug", name: "Ganda", nameLocal: "Luganda", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "UG", name: "Uganda", nameLocal: "Uganda" }],
    type: "text",
    updatedAt: "2021-05-01T09:15:10.000Z",
    audioBibles: [],
  },
  {
    id: "4d4df8722134c5ee-01",
    dblId: "4d4df8722134c5ee",
    relatedDbl: null,
    name: "Biblica® Open New Luo Translation 2020",
    nameLocal: "Biblica® Ochiw Thuolo Motingʼo Loko Manyien",
    abbreviation: "ONLT",
    abbreviationLocal: "OMLM",
    description: "Bible",
    descriptionLocal: "Muma Maler Mar Nyasaye",
    language: { id: "luo", name: "Dholuo", nameLocal: "Dholuo", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "KE", name: "Kenya", nameLocal: "Kenya" }],
    type: "text",
    updatedAt: "2021-05-01T09:08:54.000Z",
    audioBibles: [],
  },
  {
    id: "9f78f34aabe691c9-02",
    dblId: "9f78f34aabe691c9",
    relatedDbl: null,
    name: "Malayalam Indian Revised Version Bible",
    nameLocal: "മലയാളം ബൈബിള്‍",
    abbreviation: "malirv",
    abbreviationLocal: "MALIRV",
    description: "common",
    descriptionLocal: "common",
    language: { id: "mal", name: "Malayalam", nameLocal: "മലയാളം", script: "Malayalam", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-28T20:29:00.000Z",
    audioBibles: [],
  },
  {
    id: "8c49129a458d4059-01",
    dblId: "8c49129a458d4059",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) - Marathi",
    nameLocal: "इंडियन रीवाइज्ड वर्जन (IRV) - मराठी",
    abbreviation: "IRVMar",
    abbreviationLocal: "IRVMar",
    description: "Marathi Protestant Bible",
    descriptionLocal: "मराठी प्रोटेस्टंट बायबल",
    language: { id: "mar", name: "Marathi", nameLocal: "मराठी", script: "Devanagari", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T22:47:53.000Z",
    audioBibles: [],
  },
  {
    id: "385573d4ba3ff72a-01",
    dblId: "385573d4ba3ff72a",
    relatedDbl: null,
    name: "Maale Bible",
    nameLocal: "ጌኤዦ ማፃኣፖ",
    abbreviation: "MB",
    abbreviationLocal: "MB",
    description: "The Bible in Maale",
    descriptionLocal: "ጌኤዦ ማፃኣፖ",
    language: { id: "mdy", name: "Maale", nameLocal: "Male", script: "Ethiopic (Geʻez)", scriptDirection: "LTR" },
    countries: [{ id: "ET", name: "Ethiopia", nameLocal: "Ethiopia" }],
    type: "text",
    updatedAt: "2020-09-11T18:26:38.000Z",
    audioBibles: [],
  },
  {
    id: "bed82ba57f117c16-01",
    dblId: "bed82ba57f117c16",
    relatedDbl: null,
    name: "Maale New Testament",
    nameLocal: "Maale New Testament",
    abbreviation: "MNT",
    abbreviationLocal: "MNT",
    description: "New Testament",
    descriptionLocal: "New Testament",
    language: { id: "mdy", name: "Male (Ethiopia)", nameLocal: "Male (Ethiopia)", script: "Ethiopic", scriptDirection: "LTR" },
    countries: [{ id: "ET", name: "Ethiopia", nameLocal: "Ethiopia" }],
    type: "text",
    updatedAt: "2020-07-28T23:11:13.000Z",
    audioBibles: [],
  },
  {
    id: "abf017938be72f46-01",
    dblId: "abf017938be72f46",
    relatedDbl: null,
    name: "Morokodo",
    nameLocal: "Morokodo",
    abbreviation: "MKD",
    abbreviationLocal: "MKD",
    description: "Portion of Morokodo",
    descriptionLocal: "Portion of Morokodo",
    language: { id: "mgc", name: "Morokodo", nameLocal: "Morokodo", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "SS", name: "South Sudan", nameLocal: "South Sudan" }],
    type: "text",
    updatedAt: "2020-07-28T21:53:06.000Z",
    audioBibles: [],
  },
  {
    id: "b5105cd03c972046-01",
    dblId: "b5105cd03c972046",
    relatedDbl: null,
    name: "Makua New Testament",
    nameLocal: "Makua New Testament",
    abbreviation: "MNT",
    abbreviationLocal: "MNT",
    description: "Makua New Testament 2015",
    descriptionLocal: "Makua New Testament 2015",
    language: { id: "mgh", name: "Makhuwa-Meetto", nameLocal: "Makua", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-07-28T22:35:21.000Z",
    audioBibles: [],
  },
  {
    id: "f638e44feb77f803-01",
    dblId: "f638e44feb77f803",
    relatedDbl: null,
    name: "The Holy Gospel of Jesus for the Matumbi",
    nameLocal: "Injili ya Yesu",
    abbreviation: "Matumbi",
    abbreviationLocal: "Matumbi",
    description: "Luke and Acts",
    descriptionLocal: "Luka & Matendo ya Mitume",
    language: { id: "mgw", name: "Matumbi", nameLocal: "Matumbi", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2020-09-12T01:04:06.000Z",
    audioBibles: [],
  },
  {
    id: "4ffcec8e8f3c33e7-01",
    dblId: "4ffcec8e8f3c33e7",
    relatedDbl: null,
    name: "God's Holy Book in Sankaran",
    nameLocal: "Alla la Kitabu Seniman",
    abbreviation: "GHBS",
    abbreviationLocal: "AKS",
    description: "Genesis, Luke, Galatians, James",
    descriptionLocal: "A Damira, Luka, Yakuba, Kalatikailu",
    language: { id: "msc", name: "Sankaran Maninka", nameLocal: "Sankaran", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T19:38:28.000Z",
    audioBibles: [],
  },
  {
    id: "5e51f89e89947acb-01",
    dblId: "5e51f89e89947acb",
    relatedDbl: null,
    name: "Aruamu New Testament",
    nameLocal: "Godɨn Akar Aghuim; Akar Dɨkɨrɨzir Gavgavir Igiam",
    abbreviation: "AruNT",
    abbreviationLocal: "AruNT",
    description: "New Testament",
    descriptionLocal: "New Testament",
    language: { id: "msy", name: "Aruamu", nameLocal: "Aruamu", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-07-28T21:50:22.000Z",
    audioBibles: [],
  },
  {
    id: "98adf0b796dc9ff4-01",
    dblId: "98adf0b796dc9ff4",
    relatedDbl: null,
    name: "The Bible in Aruamu: Old Testament and New Testament",
    nameLocal: "Godɨn Eghaghanim: Akar Gavgavir Dɨkɨrɨzir Ghurim ko Igiam",
    abbreviation: "AruBib20",
    abbreviationLocal: "AruBib20",
    description: "Protestant",
    descriptionLocal: "Protestant",
    language: { id: "msy", name: "Aruamu", nameLocal: "Aruamu", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2021-03-07T09:09:56.000Z",
    audioBibles: [],
  },
  {
    id: "ed5744967fe39c8c-01",
    dblId: "ed5744967fe39c8c",
    relatedDbl: null,
    name: "The New Testament in Mwela",
    nameLocal: "Malagano ga Ambi",
    abbreviation: "Mwela",
    abbreviationLocal: "Shimwela",
    description: "New Testament",
    descriptionLocal: "Malagano ga Ambi",
    language: { id: "mwe", name: "Mwera", nameLocal: "Shimwela", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2021-07-19T21:14:22.000Z",
    audioBibles: [],
  },
  {
    id: "cb0425ae772bb042-01",
    dblId: "cb0425ae772bb042",
    relatedDbl: null,
    name: "The New Testament in Ndamba",
    nameLocal: "Lilaghanu lya shonu",
    abbreviation: "NdBV",
    abbreviationLocal: "NdBV",
    description: null,
    descriptionLocal: "Ndamba New Testament",
    language: { id: "ndj", name: "Ndamba", nameLocal: "Ndamba", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-09-15T05:48:13.000Z",
    audioBibles: [],
  },
  {
    id: "324f457845cb5d21-01",
    dblId: "324f457845cb5d21",
    relatedDbl: null,
    name: "Nguu New Testament",
    nameLocal: "Ndagano mp'ya kwa wanth'u wose",
    abbreviation: "NgBV",
    abbreviationLocal: "NgBV",
    description: null,
    descriptionLocal: "Nguu New Testament",
    language: { id: "ngp", name: "Nguu", nameLocal: "Ngulu", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-09-15T04:04:29.000Z",
    audioBibles: [],
  },
  {
    id: "312df00520eac624-01",
    dblId: "312df00520eac624",
    relatedDbl: null,
    name: "Takuu New Testament",
    nameLocal: "Na Taratara TeAtua i naa taratara Takuu",
    abbreviation: "NHO",
    abbreviationLocal: "Takuu",
    description: "commo",
    descriptionLocal: "commo",
    language: { id: "nho", name: "Takuu", nameLocal: "Takuu", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-15T03:59:31.000Z",
    audioBibles: [],
  },
  {
    id: "ead7b4cc5007389c-01",
    dblId: "ead7b4cc5007389c",
    relatedDbl: null,
    name: "Dutch Bible 1939",
    nameLocal: "De Heilige Schrift, Petrus Canisiusvertaling, 1939",
    abbreviation: "nld1939",
    abbreviationLocal: "NLD1939",
    description: "Catholic",
    descriptionLocal: "Katholiek",
    language: { id: "nld", name: "Dutch", nameLocal: "Nederlands", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "NL", name: "Netherlands", nameLocal: "Netherlands" }],
    type: "text",
    updatedAt: "2020-09-12T00:54:49.000Z",
    audioBibles: [],
  },
  {
    id: "43247c35dbe56e1c-01",
    dblId: "43247c35dbe56e1c",
    relatedDbl: null,
    name: "Biblica® Open God’s Word in Contemporary Chichewa 2016",
    nameLocal: "Biblica® Tsekulani Mawu a Mulungu mu Chichewa Chalero",
    abbreviation: "OCCL",
    abbreviationLocal: "OCCL",
    description: "Bible",
    descriptionLocal: "Baibulo",
    language: { id: "nya", name: "Chichewa", nameLocal: "Chichewa", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "MW", name: "Malawi", nameLocal: "Malawi" }],
    type: "text",
    updatedAt: "2021-05-11T09:10:32.000Z",
    audioBibles: [],
  },
  {
    id: "365f988242c307d2-02",
    dblId: "365f988242c307d2",
    relatedDbl: null,
    name: "Oria Indian Revised Version Bible",
    nameLocal: "ଓଡିଆ ବାଇବେଲ",
    abbreviation: "oryirv",
    abbreviationLocal: "ORYIRV",
    description: "common",
    descriptionLocal: "common",
    language: { id: "ory", name: "Odia", nameLocal: "ODIA", script: "Oriya", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T18:18:59.000Z",
    audioBibles: [],
  },
  {
    id: "e2588ba61891daa5-01",
    dblId: "e2588ba61891daa5",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Punjabi - 2019",
    nameLocal: "ਇੰਡਿਅਨ ਰਿਵਾਇਜ਼ਡ ਵਰਜ਼ਨ (IRV) - ਪੰਜਾਬੀ",
    abbreviation: "IRVPun",
    abbreviationLocal: "IRVPun",
    description: "Bible for all",
    descriptionLocal: "Bible for all",
    language: { id: "pan", name: "Panjabi", nameLocal: "ਪੰਜਾਬੀ", script: "Gurmukhi", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T06:10:36.000Z",
    audioBibles: [{ id: "439ac17466ab4ae1-01", name: "Punjabi Indian Revised Version (IRV)", nameLocal: "ਇੰਡਿਅਨ ਰਿਵਾਇਜ਼ਡ ਵਰਜ਼ਨ (IRV) - ਪੰਜਾਬੀ", dblId: "439ac17466ab4ae1" }],
  },
  {
    id: "fbb8b0e1943b417c-01",
    dblId: "fbb8b0e1943b417c",
    relatedDbl: null,
    name: "Biblica® Open Polish Living New Testament",
    nameLocal: "Biblica® Słowo Życia, otwarty dostęp™",
    abbreviation: "OPLNT",
    abbreviationLocal: "OPSZ",
    description: "The New Testament in easy to understand Polish",
    descriptionLocal: "Nowy Testament w łatwo zrozumiałym języku polskim",
    language: { id: "pol", name: "Polish", nameLocal: "Polski", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PL", name: "Poland", nameLocal: "Poland" }],
    type: "text",
    updatedAt: "2021-06-15T21:12:54.000Z",
    audioBibles: [
      {
        id: "380f44ed66bb471b-01",
        name: "Biblica® Open Polish Living New Testament Audio Edition",
        nameLocal: "Biblica® Słowo Życia, otwarty dostęp™",
        dblId: "380f44ed66bb471b",
      },
    ],
  },
  {
    id: "1c9761e0230da6e0-01",
    dblId: "1c9761e0230da6e0",
    relatedDbl: null,
    name: "Updated Gdansk Bible",
    nameLocal: "UWSPÓŁCZEŚNIONA BIBLIA GDAŃSKA",
    abbreviation: "polUBG",
    abbreviationLocal: "UBG",
    description: "Common",
    descriptionLocal: "pospolity",
    language: { id: "pol", name: "Polish", nameLocal: "Polski", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PL", name: "Poland", nameLocal: "Poland" }],
    type: "text",
    updatedAt: "2020-09-11T16:41:49.000Z",
    audioBibles: [],
  },
  {
    id: "90799bb5b996fddc-01",
    dblId: "90799bb5b996fddc",
    relatedDbl: null,
    name: "Translation for Translators in Brasilian Portuguese",
    nameLocal: "Translation for Translators in Brasilian Portuguese",
    abbreviation: "TfTP",
    abbreviationLocal: "TfTP",
    description: "common",
    descriptionLocal: "comum",
    language: { id: "por", name: "Portuguese", nameLocal: "Português", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "BR", name: "Brazil", nameLocal: "Brazil" }],
    type: "text",
    updatedAt: "2020-09-15T05:04:35.000Z",
    audioBibles: [],
  },
  {
    id: "355792a03079ccdd-01",
    dblId: "355792a03079ccdd",
    relatedDbl: null,
    name: "The New Testament in Pogoro",
    nameLocal: "Lipatanu Lya Syayi Kwa Wantu Woseri",
    abbreviation: "PBV",
    abbreviationLocal: "PBV",
    description: "New Testament",
    descriptionLocal: "New Testament",
    language: { id: "poy", name: "Shipogoro", nameLocal: "Pogolo", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-09-11T18:15:16.000Z",
    audioBibles: [],
  },
  {
    id: "33ac978af36830fa-02",
    dblId: "33ac978af36830fa",
    relatedDbl: null,
    name: "Carpathian Romani 2021",
    nameLocal: "Le Devleskero Lav Andre Romaňi Čhib Slovensko 2021",
    abbreviation: "RNC",
    abbreviationLocal: "RNC",
    description: "The Carpathian Romani Bible. Contains full NT and parts of OT that have been completed. Protestant canon.",
    descriptionLocal: "Le Devleskero Lav Andre Romaňi Čhib Slovensko 2021",
    language: { id: "rmc", name: "Romani, Carpathian", nameLocal: "Romanes", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "SK", name: "Slovakia", nameLocal: "Slovakia" },
      { id: "CZ", name: "Czechia", nameLocal: "Czechia" },
      { id: "UA", name: "Ukraine", nameLocal: "Ukraine" },
    ],
    type: "text",
    updatedAt: "2021-08-31T16:54:54.000Z",
    audioBibles: [],
  },
  {
    id: "e952663db2e91691-01",
    dblId: "e952663db2e91691",
    relatedDbl: null,
    name: "Carpathian Romani Bible",
    nameLocal: "Біблія про закарпатцько романо чіб",
    abbreviation: "ZRB",
    abbreviationLocal: "ЗРБ",
    description: "Luke and Acts",
    descriptionLocal: "Єванґеліє ле Лукастар і Апостоленґєрі бувті",
    language: { id: "rmc", name: "Romani, Carpathian", nameLocal: "Romanes", script: "Cyrillic", scriptDirection: "LTR" },
    countries: [{ id: "UA", name: "Ukraine", nameLocal: "Ukraine" }],
    type: "text",
    updatedAt: "2021-08-31T17:32:05.000Z",
    audioBibles: [],
  },
  {
    id: "6c018dd7a342aa63-01",
    dblId: "6c018dd7a342aa63",
    relatedDbl: null,
    name: "Crimean Romani Bible",
    nameLocal: "Библия опэр крымски романи чиб",
    abbreviation: "KRB",
    abbreviationLocal: "КРБ",
    description: "Ruth, Jonah Luke, Acts",
    descriptionLocal: "О Лошано Габэри катар Лука тай О дилэс э апостоленги",
    language: { id: "rmn", name: "Romani, Balkan", nameLocal: "Romani", script: "Cyrillic", scriptDirection: "LTR" },
    countries: [{ id: "UA", name: "Ukraine", nameLocal: "Ukraine" }],
    type: "text",
    updatedAt: "2021-10-08T21:10:47.000Z",
    audioBibles: [],
  },
  {
    id: "98d1c5bee401f80c-01",
    dblId: "98d1c5bee401f80c",
    relatedDbl: null,
    name: "The New Testament in Lughulu",
    nameLocal: "Laghano Lya Sambi Kwe Iwanu Wose",
    abbreviation: "LBV",
    abbreviationLocal: "LBV",
    description: "New Testament",
    descriptionLocal: "New Testament",
    language: { id: "ruf", name: "Chilughuru", nameLocal: "Luguru", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-09-11T23:28:32.000Z",
    audioBibles: [],
  },
  {
    id: "bb3df4b7c8587c77-01",
    dblId: "bb3df4b7c8587c77",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Assamese Script (সত্যৱেদঃ।)",
    nameLocal: "সত্যৱেদঃ। Sanskrit Bible (NT) in Assamese Script",
    abbreviation: "SANAS",
    abbreviationLocal: "SANAS",
    description: "Sanskrit Bible (NT) in Assamese Script (সত্যৱেদঃ।)",
    descriptionLocal: "সত্যৱেদঃ। Sanskrit Bible (NT) in Assamese Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Bengali", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T05:41:13.000Z",
    audioBibles: [],
  },
  {
    id: "8d1ad2c921d811c3-01",
    dblId: "8d1ad2c921d811c3",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Bengali Script",
    nameLocal: "সত্যবেদঃ। Sanskrit Bible (NT) in Bengali Script",
    abbreviation: "SANBN",
    abbreviationLocal: "SANBN",
    description: "Sanskrit Bible (NT) in Bengali Script (সত্যবেদঃ।)",
    descriptionLocal: "Sanskrit Bible (NT) in Bengali Script (সত্যবেদঃ।)",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Bengali", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T22:50:47.000Z",
    audioBibles: [],
  },
  {
    id: "9449d4ad98193779-01",
    dblId: "9449d4ad98193779",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Burmese Script (သတျဝေဒး၊)",
    nameLocal: "သတျဝေဒး၊ Sanskrit Bible (NT) in Burmese Script ()",
    abbreviation: "SANBU",
    abbreviationLocal: "SANBU",
    description: "Sanskrit Bible (NT) in Burmese Script (သတျဝေဒး၊)",
    descriptionLocal: "သတျဝေဒး၊ Sanskrit Bible (NT) in Burmese Script ()",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Code for uncoded script", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T23:14:02.000Z",
    audioBibles: [],
  },
  {
    id: "33b6449cacf22773-01",
    dblId: "33b6449cacf22773",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Cologne Script (satyavEdaH|)",
    nameLocal: "satyavEdaH| Sanskrit Bible (NT) in Cologne Script",
    abbreviation: "SANCO",
    abbreviationLocal: "SANCO",
    description: "Sanskrit Bible (NT) in Cologne Script (satyavEdaH|",
    descriptionLocal: "satyavEdaH| Sanskrit Bible (NT) in Cologne Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T18:11:11.000Z",
    audioBibles: [],
  },
  {
    id: "e9ea572977b4f504-01",
    dblId: "e9ea572977b4f504",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Gujarati Script (સત્યવેદઃ।)",
    nameLocal: "સત્યવેદઃ। Sanskrit Bible (NT) in Gujarati Script",
    abbreviation: "SANGJ",
    abbreviationLocal: "SANGJ",
    description: "Sanskrit Bible (NT) in Gujarati Script (સત્યવેદઃ।)",
    descriptionLocal: "સત્યવેદઃ। Sanskrit Bible (NT) in Gujarati Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Gujarati", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-29T02:20:56.000Z",
    audioBibles: [],
  },
  {
    id: "89007ccbb2eb5187-01",
    dblId: "89007ccbb2eb5187",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Harvard-Kyoto Script (satyavedaH|)",
    nameLocal: "satyavedaH| Sanskrit Bible (NT) in Harvard-Kyoto Script",
    abbreviation: "SANHK",
    abbreviationLocal: "SANHK",
    description: "Sanskrit Bible (NT) in Harvard-Kyoto Script (satyavedaH|)",
    descriptionLocal: "satyavedaH| Sanskrit Bible (NT) in Harvard-Kyoto Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T22:39:50.000Z",
    audioBibles: [],
  },
  {
    id: "0b07fcef627a2db2-01",
    dblId: "0b07fcef627a2db2",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in IAST Script (satyavedaḥ|)",
    nameLocal: "satyavedaḥ| Sanskrit Bible (NT) in IAST Script",
    abbreviation: "SANIA",
    abbreviationLocal: "SANIA",
    description: "Sanskrit Bible (NT) in IAST Script (satyavedaḥ|)",
    descriptionLocal: "satyavedaḥ| Sanskrit Bible (NT) in IAST Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T03:30:46.000Z",
    audioBibles: [],
  },
  {
    id: "d4599ff3c6b97f3a-01",
    dblId: "d4599ff3c6b97f3a",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in ISO Script (satyavēdaḥ|)",
    nameLocal: "satyavēdaḥ| Sanskrit Bible (NT) in ISO Script",
    abbreviation: "SANIS",
    abbreviationLocal: "SANIS",
    description: "Sanskrit Bible (NT) in ISO Script (satyavēdaḥ|)",
    descriptionLocal: "satyavēdaḥ| Sanskrit Bible (NT) in ISO Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-12T00:33:45.000Z",
    audioBibles: [],
  },
  {
    id: "6bc5ae3d6dd9009a-01",
    dblId: "6bc5ae3d6dd9009a",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in ITRANS Script (satyavedaH|)",
    nameLocal: "satyavedaH| Sanskrit Bible (NT) in ITRANS Script",
    abbreviation: "SANIT",
    abbreviationLocal: "SANIT",
    description: "Sanskrit Bible (NT) in ITRANS Script (satyavedaH|)",
    descriptionLocal: "satyavedaH| Sanskrit Bible (NT) in ITRANS Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T04:44:35.000Z",
    audioBibles: [],
  },
  {
    id: "c1f49ed98a65a544-01",
    dblId: "c1f49ed98a65a544",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Kannada Script (ಸತ್ಯವೇದಃ।)",
    nameLocal: "ಸತ್ಯವೇದಃ। Sanskrit Bible (NT) in Kannada Script",
    abbreviation: "SANKA",
    abbreviationLocal: "SANKA",
    description: "Sanskrit Bible (NT) in Kannada Script (ಸತ್ಯವೇದಃ।)",
    descriptionLocal: "ಸತ್ಯವೇದಃ। Sanskrit Bible (NT) in Kannada Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Kannada", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-28T23:21:16.000Z",
    audioBibles: [],
  },
  {
    id: "6bb8b0fa7aca67c6-01",
    dblId: "6bb8b0fa7aca67c6",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Khmer Script (សត្យវេទះ។)",
    nameLocal: "សត្យវេទះ។ Sanskrit Bible (NT) in Khmer Script",
    abbreviation: "SANKH",
    abbreviationLocal: "SANKH",
    description: "Sanskrit Bible (NT) in Khmer Script (សត្យវេទះ។)",
    descriptionLocal: "សត្យវេទះ។ Sanskrit Bible (NT) in Khmer Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Code for uncoded script", scriptDirection: "LTR" },
    countries: [{ id: "KH", name: "Cambodia", nameLocal: "Cambodia" }],
    type: "text",
    updatedAt: "2020-09-11T21:09:35.000Z",
    audioBibles: [],
  },
  {
    id: "119375d97b57cf04-01",
    dblId: "119375d97b57cf04",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Malayalam Script (സത്യവേദഃ।)",
    nameLocal: "സത്യവേദഃ। Sanskrit Bible (NT) in Malayalam Script",
    abbreviation: "SANML",
    abbreviationLocal: "SANML",
    description: "Sanskrit Bible (NT) in Malayalam Script (സത്യവേദഃ।)",
    descriptionLocal: "സത്യവേദഃ। Sanskrit Bible (NT) in Malayalam Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Malayalam", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T15:05:44.000Z",
    audioBibles: [],
  },
  {
    id: "5a27fd2a2de187c8-01",
    dblId: "5a27fd2a2de187c8",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Oriya Script (ସତ୍ୟୱେଦଃ।)",
    nameLocal: "ସତ୍ୟୱେଦଃ। Sanskrit Bible (NT) in Oriya Script",
    abbreviation: "SANOR",
    abbreviationLocal: "SANOR",
    description: "Sanskrit Bible (NT) in Oriya Script (ସତ୍ୟୱେଦଃ।)",
    descriptionLocal: "ସତ୍ୟୱେଦଃ। Sanskrit Bible (NT) in Oriya Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Oriya", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T20:14:18.000Z",
    audioBibles: [],
  },
  {
    id: "07225eadadcb079a-01",
    dblId: "07225eadadcb079a",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Punjabi Script (ਸਤ੍ਯਵੇਦਃ।)",
    nameLocal: "ਸਤ੍ਯਵੇਦਃ। Sanskrit Bible (NT) in Punjabi Script",
    abbreviation: "SANPN",
    abbreviationLocal: "SANPN",
    description: "Sanskrit Bible (NT) in Punjabi Script (ਸਤ੍ਯਵੇਦਃ।)",
    descriptionLocal: "ਸਤ੍ਯਵੇਦਃ। Sanskrit Bible (NT) in Punjabi Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Code for uncoded script", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T14:32:43.000Z",
    audioBibles: [],
  },
  {
    id: "2c2cf8df5a22a46e-01",
    dblId: "2c2cf8df5a22a46e",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Sinhala Script (සත්‍යවේදඃ।)",
    nameLocal: "සත්‍යවේදඃ। Sanskrit Bible (NT) in Sinhala Script",
    abbreviation: "SANSI",
    abbreviationLocal: "SANSI",
    description: "Sanskrit Bible (NT) in Sinhala Script (සත්‍යවේදඃ।)",
    descriptionLocal: "සත්‍යවේදඃ। Sanskrit Bible (NT) in Sinhala Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Code for uncoded script", scriptDirection: "LTR" },
    countries: [{ id: "LK", name: "Sri Lanka", nameLocal: "Sri Lanka" }],
    type: "text",
    updatedAt: "2020-09-11T17:41:28.000Z",
    audioBibles: [],
  },
  {
    id: "143e0e03cf5b12ae-01",
    dblId: "143e0e03cf5b12ae",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Tamil Script (ஸத்யவேத³​:।)",
    nameLocal: "ஸத்யவேத³​:। Sanskrit Bible (NT) in Tamil Script",
    abbreviation: "SANTM",
    abbreviationLocal: "SANTM",
    description: "Sanskrit Bible (NT) in Tamil Script (ஸத்யவேத³​:।)",
    descriptionLocal: "ஸத்யவேத³​:। Sanskrit Bible (NT) in Tamil Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Tamil", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T03:38:11.000Z",
    audioBibles: [],
  },
  {
    id: "aa146959e1d39b78-01",
    dblId: "aa146959e1d39b78",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Telugu Script (సత్యవేదః।)",
    nameLocal: "సత్యవేదః। Sanskrit Bible (NT) in Telugu Script",
    abbreviation: "SANTE",
    abbreviationLocal: "SANTE",
    description: "Sanskrit Bible (NT) in Telugu Script (సత్యవేదః।)",
    descriptionLocal: "సత్యవేదః। Sanskrit Bible (NT) in Telugu Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Telugu", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-28T21:14:35.000Z",
    audioBibles: [],
  },
  {
    id: "306d6ab1ca333a1e-01",
    dblId: "306d6ab1ca333a1e",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Thai Script (สตฺยเวท:ฯ)",
    nameLocal: "สตฺยเวท:ฯ Sanskrit Bible (NT) in Thai Script",
    abbreviation: "SANTH",
    abbreviationLocal: "SANTH",
    description: "Sanskrit Bible (NT) in Thai Script (สตฺยเวท:ฯ)",
    descriptionLocal: "สตฺยเวท:ฯ Sanskrit Bible (NT) in Thai Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Thai", scriptDirection: "LTR" },
    countries: [{ id: "TH", name: "Thailand", nameLocal: "Thailand" }],
    type: "text",
    updatedAt: "2020-09-11T17:57:25.000Z",
    audioBibles: [],
  },
  {
    id: "018ff00d7f55cbc1-01",
    dblId: "018ff00d7f55cbc1",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Tibetan Script (སཏྱཝེདཿ།)",
    nameLocal: "སཏྱཝེདཿ། Sanskrit Bible (NT) in Tibetan Script",
    abbreviation: "SANTI",
    abbreviationLocal: "SANTI",
    description: "Sanskrit Bible (NT) in Tibetan Script (སཏྱཝེདཿ།)",
    descriptionLocal: "སཏྱཝེདཿ། Sanskrit Bible (NT) in Tibetan Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Tibetan", scriptDirection: "LTR" },
    countries: [{ id: "CN", name: "China", nameLocal: "China" }],
    type: "text",
    updatedAt: "2020-09-11T22:13:39.000Z",
    audioBibles: [],
  },
  {
    id: "51b16e0b4b7c9825-01",
    dblId: "51b16e0b4b7c9825",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Urdu Script (سَتْیَویدَح۔)",
    nameLocal: "سَتْیَویدَح۔ Sanskrit Bible (NT) in Urdu Script",
    abbreviation: "SANUR",
    abbreviationLocal: "SANUR",
    description: "Sanskrit Bible (NT) in Urdu Script (سَتْیَویدَح۔)",
    descriptionLocal: "سَتْیَویدَح۔ Sanskrit Bible (NT) in Urdu Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Arabic", scriptDirection: "RTL" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T19:43:27.000Z",
    audioBibles: [],
  },
  {
    id: "9a875168ff4df1a3-01",
    dblId: "9a875168ff4df1a3",
    relatedDbl: null,
    name: "Sanskrit Bible (NT) in Velthuis Script (satyaveda.h|)",
    nameLocal: "satyaveda.h| Sanskrit Bible (NT) in Velthuis Script",
    abbreviation: "SANVE",
    abbreviationLocal: "SANVE",
    description: "Sanskrit Bible (NT) in Velthuis Script (satyaveda.h|)",
    descriptionLocal: "satyaveda.h| Sanskrit Bible (NT) in Velthuis Script",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T23:35:58.000Z",
    audioBibles: [],
  },
  {
    id: "e8b40ccabe793c0d-01",
    dblId: "e8b40ccabe793c0d",
    relatedDbl: null,
    name: "Sanskrit NT in Devanagari",
    nameLocal: "सत्यवेदः। Sanskrit NT in Devanagari",
    abbreviation: "SAN-DN",
    abbreviationLocal: "SAN-DN",
    description: "Sanskrit NT in Devanagari",
    descriptionLocal: "सत्यवेदः। Sanskrit NT in Devanagari",
    language: { id: "san", name: "Sanskrit", nameLocal: "Saṃskṛtam", script: "Devanagari", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-07-29T02:15:00.000Z",
    audioBibles: [],
  },
  {
    id: "f95e2d9b384f8e6e-01",
    dblId: "f95e2d9b384f8e6e",
    relatedDbl: null,
    name: "Caning Bible Translation",
    nameLocal: "Sorunu Kaläg na Ikä Caning",
    abbreviation: "SHJ",
    abbreviationLocal: "SHJ",
    description: "Gospel of Luke",
    descriptionLocal: "Inycil Luka na Ikä Caning",
    language: { id: "shj", name: "Shatt", nameLocal: "Shatt", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "SS", name: "South Sudan", nameLocal: "South Sudan" }],
    type: "text",
    updatedAt: "2020-06-22T20:02:00.000Z",
    audioBibles: [],
  },
  {
    id: "592420522e16049f-01",
    dblId: "592420522e16049f",
    relatedDbl: null,
    name: "Reina Valera 1909",
    nameLocal: "Reina Valera 1909",
    abbreviation: "RVR09",
    abbreviationLocal: "RVR09",
    description: "Biblia Reina Valera 1909",
    descriptionLocal: "Biblia Reina Valera 1909",
    language: { id: "spa", name: "Spanish", nameLocal: "Español", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "ZZ", name: "Unspecific", nameLocal: "Unspecific" }],
    type: "text",
    updatedAt: "2021-05-25T18:11:22.000Z",
    audioBibles: [],
  },
  {
    id: "b32b9d1b64b4ef29-01",
    dblId: "b32b9d1b64b4ef29",
    relatedDbl: null,
    name: "The Holy Bible in Simple Spanish",
    nameLocal: "La Biblia en Español Sencillo",
    abbreviation: "spabes",
    abbreviationLocal: "BES",
    description: "Common",
    descriptionLocal: "Común",
    language: { id: "spa", name: "Spanish", nameLocal: "Español", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "MX", name: "Mexico", nameLocal: "Mexico" }],
    type: "text",
    updatedAt: "2021-07-08T21:11:27.000Z",
    audioBibles: [],
  },
  {
    id: "482ddd53705278cc-01",
    dblId: "482ddd53705278cc",
    relatedDbl: null,
    name: "The New Testament in Spanish, Free Bible Version",
    nameLocal: "El Nuevo Testamento, Versión Biblia Libre",
    abbreviation: "VBL",
    abbreviationLocal: "VBL",
    description: "common",
    descriptionLocal: "Nuevo Testmento",
    language: { id: "spa", name: "Spanish", nameLocal: "Español", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "ES", name: "Spain", nameLocal: "Spain" }],
    type: "text",
    updatedAt: "2021-05-25T18:12:21.000Z",
    audioBibles: [],
  },
  {
    id: "2a65010324d677b6-01",
    dblId: "2a65010324d677b6",
    relatedDbl: null,
    name: "Akukem Portions for DBL",
    nameLocal: "Mak Osɨrisira Akaman Aghuuŋ ko Iesusɨm Mbɨsevisir Gumasi",
    abbreviation: "Akg-MkAc",
    abbreviationLocal: "Akg-MkAc",
    description: null,
    descriptionLocal: "Published Mark & Acts",
    language: { id: "spm", name: "Akukem", nameLocal: "Akɨghɨman Akam", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-15T03:55:45.000Z",
    audioBibles: [],
  },
  {
    id: "06995ce9cd23361b-01",
    dblId: "06995ce9cd23361b",
    relatedDbl: null,
    name: "Serbian Bible",
    nameLocal: "Sveta Biblija",
    abbreviation: "srp1865",
    abbreviationLocal: "SRP1865",
    description: "common",
    descriptionLocal: "zajednički",
    language: { id: "srp", name: "Serbian", nameLocal: "Српски/ Srpski", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "RS", name: "Serbia", nameLocal: "Serbia" }],
    type: "text",
    updatedAt: "2020-09-11T14:30:52.000Z",
    audioBibles: [],
  },
  {
    id: "bbeb583cd75c6356-01",
    dblId: "bbeb583cd75c6356",
    relatedDbl: null,
    name: "Susu Bible",
    nameLocal: "Soso Kitaabuie: Tawureta, Yabura, Inyila",
    abbreviation: "Susu",
    abbreviationLocal: "Soso",
    description: "Bible in three volumes",
    descriptionLocal: "Soso Kitaabuie",
    language: { id: "sus", name: "Susu", nameLocal: "Susu", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-07-28T23:00:03.000Z",
    audioBibles: [],
  },
  {
    id: "2d5220a02a7aaac6-01",
    dblId: "2d5220a02a7aaac6",
    relatedDbl: null,
    name: "Susu Bible in Arabic Script",
    nameLocal: "Ala xa Kitaabui Sosoe bɛ",
    abbreviation: "AKS",
    abbreviationLocal: "AKS",
    description: "Protestant",
    descriptionLocal: "Tawureta Munsa, Yabura Dawuda, Inyila Isa",
    language: { id: "sus", name: "Susu", nameLocal: "Susu", script: "Arabic", scriptDirection: "RTL" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T17:44:29.000Z",
    audioBibles: [],
  },
  {
    id: "fa4317c59f0825e0-01",
    dblId: "fa4317c59f0825e0",
    relatedDbl: null,
    name: "Swedish Core Bible - expanded",
    nameLocal: "Svenska Kärnbibeln",
    abbreviation: "SKB",
    abbreviationLocal: "SKB",
    description: "En expanderad översättning",
    descriptionLocal: "En expanderad översättning",
    language: { id: "swe", name: "Swedish", nameLocal: "Svenska", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "SE", name: "Sweden", nameLocal: "Sweden" }],
    type: "text",
    updatedAt: "2021-03-19T09:12:42.000Z",
    audioBibles: [],
  },
  {
    id: "611f8eb23aec8f13-01",
    dblId: "611f8eb23aec8f13",
    relatedDbl: null,
    name: "Biblica® Open Kiswahili Contemporary Version (Neno) 2015",
    nameLocal: "Biblica® Toleo Wazi Neno: Bibilia Takatifu",
    abbreviation: "ONEN",
    abbreviationLocal: "ONEN",
    description: "Protestant Bible",
    descriptionLocal: "Protestant Bible",
    language: { id: "swh", name: "Swahili", nameLocal: "Kiswahili", script: "Latin", scriptDirection: "LTR" },
    countries: [
      { id: "KE", name: "Kenya", nameLocal: "Kenya" },
      { id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" },
    ],
    type: "text",
    updatedAt: "2021-05-01T09:10:19.000Z",
    audioBibles: [],
  },
  {
    id: "03a021185023710b-01",
    dblId: "03a021185023710b",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Tamil - 2019",
    nameLocal: "இண்டியன் ரிவைஸ்டு வெர்ஸன் (IRV) - தமிழ்",
    abbreviation: "IRVTam",
    abbreviationLocal: "IRVTam",
    description: "Protestant Bible for all",
    descriptionLocal: "Protestant Bible for all",
    language: { id: "tam", name: "Tamil", nameLocal: "தமிழ்", script: "Tamil", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-11T14:19:29.000Z",
    audioBibles: [],
  },
  {
    id: "8e3b1a957009c6ca-01",
    dblId: "8e3b1a957009c6ca",
    relatedDbl: null,
    name: "New Testament in Tay",
    nameLocal: "Jisas Klays Takaw Teplep Ne",
    abbreviation: "TayNT",
    abbreviationLocal: "TayNT",
    description: "New Testament",
    descriptionLocal: "New Testament",
    language: { id: "taw", name: "Tay", nameLocal: "Tai", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T22:53:12.000Z",
    audioBibles: [],
  },
  {
    id: "5b835ce16a1703ff-01",
    dblId: "5b835ce16a1703ff",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Telugu - 2019",
    nameLocal: "ఇండియన్ రివైజ్డ్ వెర్షన్ (IRV) - తెలుగు -2019",
    abbreviation: "IRVTel",
    abbreviationLocal: "IRVTel",
    description: "Bible for all",
    descriptionLocal: "Bible for all",
    language: { id: "tel", name: "Telugu", nameLocal: "తెలుగు", script: "Telugu", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T04:33:34.000Z",
    audioBibles: [],
  },
  {
    id: "2eb94132ad61ae75-01",
    dblId: "2eb94132ad61ae75",
    relatedDbl: null,
    name: "Thai KJV",
    nameLocal: "พระคัมภีร์ภาษาไทยฉบับ KJV",
    abbreviation: "KJV",
    abbreviationLocal: "KJV",
    description: "Protestant",
    descriptionLocal: "โปรเตสแตนต์",
    language: { id: "tha", name: "Thai", nameLocal: "ไทย", script: "Thai", scriptDirection: "LTR" },
    countries: [{ id: "TH", name: "Thailand", nameLocal: "Thailand" }],
    type: "text",
    updatedAt: "2020-09-11T17:48:57.000Z",
    audioBibles: [],
  },
  {
    id: "30cb581bcc911c45-01",
    dblId: "30cb581bcc911c45",
    relatedDbl: null,
    name: "God's Book in Toma",
    nameLocal: "GALA Sɛʋɛi",
    abbreviation: "GS",
    abbreviationLocal: "GS",
    description: "portions",
    descriptionLocal: "portions",
    language: { id: "tod", name: "Toma", nameLocal: "Toma", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-09-11T17:59:45.000Z",
    audioBibles: [],
  },
  {
    id: "25210406001d9aae-01",
    dblId: "25210406001d9aae",
    relatedDbl: null,
    name: "Tongan Revised West Translation",
    nameLocal: "KO E TOHI TAPU KĀTOA",
    abbreviation: "tonRWV",
    abbreviationLocal: "RWV",
    description: "The Holy Bible in Tongan, Revised West Translation",
    descriptionLocal: "The Holy Bible in Tongan, Revised West Translation",
    language: { id: "ton", name: "Tonga (Tonga Islands)", nameLocal: "lea fakatonga", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TO", name: "Tonga", nameLocal: "Tonga" }],
    type: "text",
    updatedAt: "2020-09-11T17:08:18.000Z",
    audioBibles: [],
  },
  {
    id: "b6aee081108c0bc6-01",
    dblId: "b6aee081108c0bc6",
    relatedDbl: null,
    name: "Biblica® Open Akuapem Twi Contemporary Bible 2020",
    nameLocal: "Biblica® Wonhia ɛho kwamma nhoma Akuapem Twi Nkwa Asɛm",
    abbreviation: "OAKCB",
    abbreviationLocal: "WAKNA",
    description: "Bible",
    descriptionLocal: "Apam Dedaw ne Apam Foforo",
    language: { id: "twi", name: "Twi", nameLocal: "Twi", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GH", name: "Ghana", nameLocal: "Ghana" }],
    type: "text",
    updatedAt: "2021-02-11T09:10:51.000Z",
    audioBibles: [
      {
        id: "6e21c09d8edb4838-01",
        name: "Biblica® Open Akuapem Twi Contemporary Bible™, Audio Edition",
        nameLocal: "Biblica® Wonhia Akuapem Twi Nkwa Asɛm™ ho kwamma nhoma, Nea Wotie",
        dblId: "6e21c09d8edb4838",
      },
    ],
  },
  {
    id: "18f6cf27f7b43297-01",
    dblId: "18f6cf27f7b43297",
    relatedDbl: null,
    name: "Biblica® Open Asante Twi Contemporary Bible 2020",
    nameLocal: "Biblica® Wɔnhia ɛho kwamma nwoma Asante Twi Nkwa Asɛm",
    abbreviation: "OASCB",
    abbreviationLocal: "WASNA",
    description: "Biible",
    descriptionLocal: "Apam Dada ne Apam Foforɔ",
    language: { id: "twi", name: "Twi", nameLocal: "Twi", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "GH", name: "Ghana", nameLocal: "Ghana" }],
    type: "text",
    updatedAt: "2021-01-29T09:08:23.000Z",
    audioBibles: [
      {
        id: "03d2ea6f8f7c4a19-01",
        name: "Biblica® Open Asante Twi Contemporary Bible™, Audio Edition",
        nameLocal: "Biblica® Wɔnhia ɛho kwamma nwoma Asante Twi Nkwa Asɛm™, Deɛ Wɔtie",
        dblId: "03d2ea6f8f7c4a19",
      },
    ],
  },
  {
    id: "de0270810140edf9-01",
    dblId: "de0270810140edf9",
    relatedDbl: null,
    name: "Indian Revised Version (IRV) Urdu - 2019",
    nameLocal: "इंडियन रिवाइज्ड वर्जन (IRV) उर्दू - 2019",
    abbreviation: "IRVUrd",
    abbreviationLocal: "IRVUrd",
    description: "Urdu Bible for All",
    descriptionLocal: "Urdu Bible for All",
    language: { id: "urd", name: "Urdu", nameLocal: "اردو", script: "Devanagari", scriptDirection: "LTR" },
    countries: [{ id: "IN", name: "India", nameLocal: "India" }],
    type: "text",
    updatedAt: "2020-09-15T06:04:45.000Z",
    audioBibles: [],
  },
  {
    id: "e01f11e9b4b8e338-01",
    dblId: "e01f11e9b4b8e338",
    relatedDbl: null,
    name: "Sob Jonah and Luke",
    nameLocal: "Profet Yonab / Dora Nama Lukede Feiaga",
    abbreviation: "SobP15",
    abbreviationLocal: "SobP15",
    description: "Sob Portions 15",
    descriptionLocal: "Sob Portions",
    language: { id: "urw", name: "Sop", nameLocal: "Sob Dora", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "PG", name: "Papua New Guinea", nameLocal: "Papua New Guinea" }],
    type: "text",
    updatedAt: "2020-09-15T06:06:57.000Z",
    audioBibles: [],
  },
  {
    id: "c2d40ebca6db1ec5-01",
    dblId: "c2d40ebca6db1ec5",
    relatedDbl: null,
    name: "The Bible in Vidunda",
    nameLocal: "Ilagano lya Katali, Ilagano Linyale kwa Wanhu Weng’ha",
    abbreviation: "Vidunda",
    abbreviationLocal: "Chividunda",
    description: "New Testament, Pentateuch",
    descriptionLocal: "Chividunda",
    language: { id: "vid", name: "Vidunda", nameLocal: "Chividunda", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2020-09-15T05:45:32.000Z",
    audioBibles: [],
  },
  {
    id: "5cc7093967a0a392-01",
    dblId: "5cc7093967a0a392",
    relatedDbl: null,
    name: "Biblica® Open Vietnamese Contemporary Bible 2015",
    nameLocal: "Biblica® Thiên Ban Kinh Thánh Hiện Đại",
    abbreviation: "OVCB",
    abbreviationLocal: "OVCB",
    description: "Protestant Bible",
    descriptionLocal: "Kinh Thánh",
    language: { id: "vie", name: "Vietnamese", nameLocal: "Tiếng Việt", script: "Code for inherited script", scriptDirection: "LTR" },
    countries: [{ id: "VN", name: "Viet Nam", nameLocal: "Viet Nam" }],
    type: "text",
    updatedAt: "2021-05-01T09:09:32.000Z",
    audioBibles: [],
  },
  {
    id: "1b878de073afef07-01",
    dblId: "1b878de073afef07",
    relatedDbl: null,
    name: "Vietnamese Bible (1934)",
    nameLocal: "Vietnamese Bible (1934)",
    abbreviation: "vie1934",
    abbreviationLocal: "VIE1934",
    description: "common",
    descriptionLocal: "chung",
    language: { id: "vie", name: "Vietnamese", nameLocal: "Tiếng Việt", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "VN", name: "Viet Nam", nameLocal: "Viet Nam" }],
    type: "text",
    updatedAt: "2020-09-11T16:38:07.000Z",
    audioBibles: [],
  },
  {
    id: "afe8f67d8ba9025c-01",
    dblId: "afe8f67d8ba9025c",
    relatedDbl: null,
    name: "Yalunka Bible",
    nameLocal: "Kisin Kiraan Kitabuna",
    abbreviation: "Yalb",
    abbreviationLocal: "Kitabuna",
    description: "Protestant Bible",
    descriptionLocal: "Protestant Bible",
    language: { id: "yal", name: "Yalunka", nameLocal: "Yalunka", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "GN", name: "Guinea", nameLocal: "Guinea" }],
    type: "text",
    updatedAt: "2020-09-15T05:26:07.000Z",
    audioBibles: [],
  },
  {
    id: "8a448a0135a6a70a-01",
    dblId: "8a448a0135a6a70a",
    relatedDbl: null,
    name: "Yapese Bible",
    nameLocal: "Bible Ni Thothup",
    abbreviation: "yap",
    abbreviationLocal: "YAP",
    description: "common",
    descriptionLocal: "common",
    language: { id: "yap", name: "Yapese", nameLocal: "Yapese", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "FM", name: "Micronesia, Federated States of", nameLocal: "Micronesia, Federated States of" }],
    type: "text",
    updatedAt: "2020-09-11T22:44:16.000Z",
    audioBibles: [],
  },
  {
    id: "b8d1feac6e94bd74-01",
    dblId: "b8d1feac6e94bd74",
    relatedDbl: null,
    name: "Biblica® Open Yoruba Contemporary Bible 2017",
    nameLocal: "Biblica® ní oore ọ̀fẹ́ láti lo Bíbélì Mímọ́ ní Èdè Yorùbá Òde-Òní™",
    abbreviation: "OYCB",
    abbreviationLocal: "BMYO",
    description: "Protestant Bible",
    descriptionLocal: "Bíbélì Mímọ́",
    language: { id: "yor", name: "Yoruba", nameLocal: "Yorùbá", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "NG", name: "Nigeria", nameLocal: "Nigeria" }],
    type: "text",
    updatedAt: "2021-05-01T09:13:18.000Z",
    audioBibles: [
      {
        id: "2691a33c58f144c3-01",
        name: "Biblica® Open Yoruba Contemporary Bible, Audio Edition",
        nameLocal: "Biblica® ní oore ọ̀fẹ́ láti lo Bíbélì Mímọ́ ní Èdè Yorùbá Òde-Òní™, Ẹ̀dà Aláfetígbó",
        dblId: "2691a33c58f144c3",
      },
    ],
  },
  {
    id: "7e7a704dd32c4280-01",
    dblId: "7e7a704dd32c4280",
    relatedDbl: null,
    name: "The New Testament in Zaramo",
    nameLocal: "Lagano da Isambi da Mndewa na Mkombola Wetu Yesu Kilisto",
    abbreviation: "Kizalamo",
    abbreviationLocal: "Kizalamo",
    description: "New Testament in Zaramo",
    descriptionLocal: "Lagano da Isambi Muulonzi wa Kizalamo",
    language: { id: "zaj", name: "Zaramo", nameLocal: "Kizalamo", script: "Latin", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania, United Republic of", nameLocal: "Tanzania, United Republic of" }],
    type: "text",
    updatedAt: "2021-07-19T21:10:47.000Z",
    audioBibles: [],
  },
  {
    id: "c9f3cf58d557a9f3-01",
    dblId: "c9f3cf58d557a9f3",
    relatedDbl: null,
    name: "The New Testament in Zigua",
    nameLocal: "Lagano hya",
    abbreviation: "ZiBT",
    abbreviationLocal: "ZiBT",
    description: "Zigua NT",
    descriptionLocal: "Zigua NT",
    language: { id: "ziw", name: "Zigua", nameLocal: "Zigula", script: "Roman", scriptDirection: "LTR" },
    countries: [{ id: "TZ", name: "Tanzania", nameLocal: "Tanzania" }],
    type: "text",
    updatedAt: "2020-09-15T05:47:14.000Z",
    audioBibles: [],
  },
]
