export type SaveList = SaveListSettings | SaveListSyncedSettings | "themes" | "events" | "templates" | "driveKeys"

export type SaveListSyncedSettings = "categories" | "drawSettings" | "overlayCategories" | "templateCategories" | "timers" | "variables" | "triggers" | "scriptures" | "scriptureSettings" | "groups" | "midiIn" | "videoMarkers" | "customizedIcons"

export type SaveListSettings =
    | "initialized"
    | "activeProject"
    | "alertUpdates"
    | "audioFolders"
    | "autoOutput"
    | "autosave"
    | "timeFormat"
    | "defaultProjectName"
    | "showsPath"
    | "exportPath"
    | "scripturePath"
    | "recordingPath"
    | "lockedOverlays"
    | "drawer"
    | "drawerTabsData"
    | "groupNumbers"
    | "fullColors"
    | "formatNewShow"
    | "imageExtensions"
    | "labelsDisabled"
    | "language"
    | "maxConnections"
    | "mediaFolders"
    | "mediaOptions"
    | "openedFolders"
    | "os"
    | "outputs"
    | "sorted"
    | "styles"
    | "outLocked"
    | "presenterControllerKeys"
    | "playerVideos"
    | "ports"
    | "disabledServers"
    | "serverData"
    | "remotePassword"
    | "resized"
    | "slidesOptions"
    | "splitLines"
    | "theme"
    | "transitionData"
    | "videoExtensions"
    | "webFavorites"
    | "volume"
    | "gain"
    | "driveData"
    | "calendarAddShow"
    | "special"
    | "deviceId"
