// AI AUTO SCRIPTURE - biblical proper nouns for speech-to-text vocabulary biasing
// GENERATED FILE - do not edit. Regenerate with: node scripts/generateBibleVocabulary.js
// Sources: AMP, AMPC, ASV, BBE, BSB, CEB, CEV, CSB, ERV, ESV, GNT, GW, HCSB, KJ21, KJV 2000, KJV, MSG 18, MSG, NASB 95, NASB, NCV, NIRV, NIV, NKJV, NLT, NRSV, RSV, TLB, TPT, WEB, YLT

/** Biblical names/places/peoples ranked hardest-to-transcribe first (complexity, then frequency). */
export const BIBLE_NAMES_RANKED: string[] = [
    "Jerusalem",
    "Israelites",
    "Philistines",
    "Benjamin",
    "Jeremiah",
    "Manasseh",
    "Hezekiah",
    "Jonathan",
    "Jeroboam",
    "Egyptians",
    "Pharisees",
    "Nebuchadnezzar",
    "Jehoshaphat",
    "Zedekiah",
    "Amorites",
    "Abimelech",
    "Damascus",
    "Mordecai",
    "Philistine",
    "Ammonites",
    "Rehoboam",
    "Zechariah",
    "Canaanites",
    "Naphtali",
    "Jehoiada",
    "Bethlehem",
    "Chaldeans",
    "Israelite",
    "Issachar",
    "Shemaiah",
    "Jehoiakim",
    "Egyptian",
    "Euphrates",
    "Barnabas",
    "Gedaliah",
    "Jephthah",
    "Abiathar",
    "Hananiah",
    "Arameans",
    "Adonijah",
    "Babylonia",
    "Nazareth",
    "Amalekites",
    "Phinehas",
    "Hittites",
    "Meshullam",
    "Jebusites",
    "Zerubbabel",
    "Macedonia",
    "Tarshish",
    "Beersheba",
    "Ben-hadad",
    "Gomorrah",
    "Maaseiah",
    "Jehoahaz",
    "Jehoiachin",
    "Babylonians",
    "Canaanite",
    "Ahithophel",
    "Hadadezer",
    "Moabites",
    "Ahasuerus",
    "Caesarea",
    "Perizzites",
    "Nethaniah",
    "Reubenites",
    "Athaliah",
    "Anathoth",
    "Capernaum",
    "Ahimelech",
    "Mephibosheth",
    "Eliashib",
    "Mattaniah",
    "Midianites",
    "Elishama",
    "Sennacherib",
    "Obed-edom",
    "Artaxerxes",
    "Hashabiah",
    "Jephunneh",
    "Mediterranean",
    "Amminadab",
    "Ammonite",
    "Nebuzaradan",
    "Shadrach",
    "Sadducees",
    "Jeduthun",
    "Jebusite",
    "Edomites",
    "Pharisee",
    "Melchizedek",
    "Mahanaim",
    "Ethiopia",
    "Shephatiah",
    "Kohathites",
    "Assyrian",
    "Barzillai",
    "Assyrians",
    "Nethanel",
    "Ashkelon",
    "Shealtiel",
    "Barabbas",
    "Abinadab",
    "Magdalene",
    "Remaliah",
    "Iscariot",
    "Beth-shemesh",
    "Ramoth-gilead",
    "Sidonians",
    "Cornelius",
    "Benjaminites",
    "Zalmunna",
    "Babylonian",
    "Bathsheba",
    "Zephaniah",
    "Abednego",
    "Hallelujah",
    "Christian",
    "Zelophehad",
    "Philistia",
    "Sanballat",
    "Beer-sheba",
    "Shelemiah",
    "Christians",
    "Kiriath-jearim",
    "Belteshazzar",
    "Caiaphas",
    "Elizabeth",
    "Gershonites",
    "Malchijah",
    "Jerubbaal",
    "Shecaniah",
    "Zebadiah",
    "Nehemiah",
    "Ish-bosheth",
    "Midianite",
    "Makkedah",
    "Ashtaroth",
    "Berechiah",
    "Jerahmeel",
    "Azmaveth",
    "Rabshakeh",
    "Jehohanan",
    "Sherebiah",
    "Belshazzar",
    "Mattithiah",
    "Mareshah",
    "Eliphelet",
    "Beth-horon",
    "Ethiopians",
    "Beth-el",
    "Samaritan",
    "Jerimoth",
    "Michmash",
    "Thessalonica",
    "Gileadite",
    "Jeshaiah",
    "Gamaliel",
    "Elioenai",
    "Bethsaida",
    "Gibeonites",
    "Elnathan",
    "Meraioth",
    "Jehozadak",
    "Herodias",
    "Methuselah",
    "Oholibamah",
    "Shelomith",
    "Shebaniah",
    "Nebuchadrezzar",
    "Philippi",
    "Jeremoth",
    "Mahalalel",
    "Basemath",
    "Alexander",
    "Jabesh-gilead",
    "Meremoth",
    "Cherethites",
    "Jahaziel",
    "Sanhedrin",
    "Nathanael",
    "Laodicea",
    "Shunammite",
    "Samaritans",
    "Tahpanhes",
    "Benjamites",
    "Jezreelite",
    "Nazarene",
    "Oholibah",
    "Ethiopian",
    "Sepharvaim",
    "Eliasaph",
    "Kiriathaim",
    "Mesopotamia",
    "Jeconiah",
    "Benhadad",
    "Elimelech",
    "Pelethites",
    "Machpelah",
    "Nicodemus",
    "Gibbethon",
    "Kadesh-barnea",
    "Netophathite",
    "Hazeroth",
    "Rephaiah",
    "Priscilla",
    "Ishmaelites",
    "Girgashites",
    "Tychicus",
    "Paddan-aram",
    "Alphaeus",
    "Aristarchus",
    "Eshtemoa",
    "Zerahiah",
    "Persians",
    "Gemariah",
    "Arphaxad",
    "Pelatiah",
    "Rephidim",
    "Shelumiel",
    "Arpachshad",
    "Netophah",
    "Pamphylia",
    "Potiphar",
    "Benjaminite",
    "Zurishaddai",
    "Pedahzur",
    "Temanite",
    "Ephrathah",
    "Hammedatha",
    "Nethinim",
    "Gershonite",
    "Ammishaddai",
    "Perizzite",
    "Tishbite",
    "Kiriath-arba",
    "Amalekite",
    "Hodaviah",
    "Rehabiah",
    "Pahath-moab",
    "Kohathite",
    "Nebaioth",
    "Geshurites",
    "Benjamite",
    "Hagrites",
    "Horonaim",
    "Ishbosheth",
    "Ephraimites",
    "Galilean",
    "Jaazaniah",
    "Bartholomew",
    "Pekahiah",
    "Chaldean",
    "Korahites",
    "Merarites",
    "Shuthelah",
    "Jehozabad",
    "Galileans",
    "Malkijah",
    "Hushathite",
    "Meshelemiah",
    "Sheshbazzar",
    "Thyatira",
    "Hebronites",
    "Ebed-melech",
    "Kedemoth",
    "Mephaath",
    "Shelomoth",
    "Shimshai",
    "Jehonadab",
    "Shemiramoth",
    "Pethahiah",
    "Tiglath-pileser",
    "Zacchaeus",
    "Shemariah",
    "Baal-hanan",
    "Hararite",
    "Zarephath",
    "Ezion-geber",
    "Beth-aven",
    "Tattenai",
    "Sibbecai",
    "Beelzebul",
    "Shilonite",
    "Jeshimon",
    "Elizaphan",
    "Peninnah",
    "Beth-lehem",
    "Chenaanah",
    "Abed-nego",
    "God-fearing",
    "Arimathea",
    "Phoenicia",
    "Ashtoreth",
    "Zacharias",
    "Chedorlaomer",
    "Pentecost",
    "Simeonites",
    "Ephraimite",
    "Moabitess",
    "Demetrius",
    "Baptizer",
    "Zipporah",
    "Golgotha",
    "Ebiasaph",
    "Lebo-hamath",
    "Manahath",
    "Claudius",
    "Jeshurun",
    "Jashobeam",
    "Trophimus",
    "Epaphras",
    "Togarmah",
    "Carchemish",
    "Naamathite",
    "Adoniram",
    "Baal-zebub",
    "Stephanas",
    "Chephirah",
    "Beth-shean",
    "Sharezer",
    "Shabbethai",
    "Bakbukiah",
    "Berekiah",
    "Chinnereth",
    "Zarethan",
    "Adonikam",
    "Mattenai",
    "Israelis",
    "Daberath",
    "Pirathonite",
    "Tiberias",
    "Ashkenaz",
    "Mehetabel",
    "Jotbathah",
    "Miniamin",
    "Gennesaret",
    "Adrammelech",
    "Rehoboth",
    "Mahalath",
    "Manassites",
    "Hoshaiah",
    "Ahisamach",
    "Gileadites",
    "Shaaraim",
    "Jekamiah",
    "Meshezabel",
    "Bethphage",
    "Onesimus",
    "Ephesians",
    "Shethar-bozenai",
    "Kenizzite",
    "Merib-baal",
    "Pleiades",
    "Carmelite",
    "Beerothite",
    "Shalmaneser",
    "Immanuel",
    "Merarite",
    "Izharites",
    "Pirathon",
    "Maacathite",
    "Rechabites",
    "Kibroth-hattaavah",
    "Ebenezer",
    "Tahpenes",
    "Horonite",
    "Historical",
    "Conaniah",
    "Silvanus",
    "Zerahites",
    "Pelonite",
    "Ishmaelite",
    "En-gedi",
    "Interlude",
    "Potiphera",
    "Ben-hinnom",
    "Malchiah",
    "Chaldaeans",
    "Netophathites",
    "Alexandria",
    "Tertullus",
    "Meunites",
    "Ginnethon",
    "Onesiphorus",
    "Malchiel",
    "En-rogel",
    "Chenaniah",
    "Arabians",
    "Herodians",
    "Mattathias",
    "Malchishua",
    "Jerub-Baal",
    "Jochebed",
    "Maacathites",
    "Beth-peor",
    "Beth-zur",
    "Hachilah",
    "Habakkuk",
    "Aramaeans",
    "Anakites",
    "Adullamite",
    "Beth-jeshimoth",
    "Gath-rimmon",
    "Beth-shan",
    "Rephaites",
    "Achshaph",
    "Lo-debar",
    "Mithredath",
    "Epaphroditus",
    "Fire-Gift",
    "Abimelek",
    "Hazar-shual",
    "Philadelphia",
    "Cushites",
    "Nephilim",
    "Kiriath-sepher",
    "Jehosheba",
    "Jehonathan",
    "Baal-perazim",
    "Tirhakah",
    "Meshillemoth",
    "Matthias",
    "Sosthenes",
    "Archippus",
    "Hymenaeus",
    "Nehelamite",
    "Elzaphan",
    "Shaalbim",
    "Decapolis",
    "Thaddaeus",
    "Hazarmaveth",
    "Dinhabah",
    "Masrekah",
    "Jogbehah",
    "Beth-arabah",
    "Madmannah",
    "Gederoth",
    "Ezrahite",
    "Shimeath",
    "Tanhumeth",
    "Sheariah",
    "Jehoiarib",
    "Jekameam",
    "Jehdeiah",
    "Eliathah",
    "Mallothi",
    "Mahazioth",
    "Tabbaoth",
    "Gethsemane",
    "Bithynia",
    "Zachariah",
    "Nebuchadnez",
    "Mehujael",
    "Nephtoah",
    "Zemaraim",
    "Adoni-bezek",
    "Cushan-rishathaim",
    "Abiezrites",
    "Ziphites",
    "Esarhaddon",
    "Ishmaiah",
    "Giddalti",
    "Joshbekashah",
    "Theophilus",
    "Cappadocia",
    "Nicolaitans",
    "Deuteronomy",
    "Kehelathah",
    "Makheloth",
    "Hashmonah",
    "Moseroth",
    "Hazar-enan",
    "Izrahiah",
    "Mikneiah",
    "Hallohesh",
    "Shulammite",
    "Amraphel",
    "Zalmonah",
    "Joshaphat",
    "Shophach",
    "Elamites",
    "Mahseiah",
    "Ashpenaz",
    "Bethshemesh",
    "Akrabbim",
    "Zillethai",
    "Thessalonians",
    "Joktheel",
    "Jezreelitess",
    "Genubath",
    "Reubenite",
    "Barsabbas",
    "Areopagus",
    "Nergal-sharezer",
    "Beelzebub",
    "Anathothite",
    "Girgashite",
    "Pi-hahiroth",
    "Nahaliel"
]

/** The most frequent distinctive names per bible book (1-66), for passage-aware prompts. */
export const BIBLE_NAMES_BY_BOOK: Record<number, string[]> = {
    1: ["Isaac", "Abram", "Laban", "Canaan", "Rachel", "Sarah", "Rebekah", "Abimelech", "Sodom", "Shechem", "Benjamin", "Ishmael", "Sarai", "Nahor", "Hagar"],
    2: ["Egyptians", "Sinai", "Jethro", "Isaac", "Egyptian", "Hebrews", "Bezalel", "Hebrew", "Canaanites", "Amalek", "Midian", "Israelite", "Hivites", "Hittites", "Oholiab"],
    3: ["Israelite", "Sinai", "Molech", "Canaan", "Eleazar", "Ithamar", "Azazel", "Nadab", "Abihu", "Egyptian", "Fire-Gift", "Mishael", "Dibri", "Isaac", "Elzaphan"],
    4: ["Balaam", "Balak", "Eleazar", "Jordan", "Manasseh", "Reuben", "Korah", "Ephraim", "Sinai", "Canaan", "Asher", "Amorites", "Benjamin", "Issachar", "Gilead"],
    5: ["Jordan", "Bashan", "Sihon", "Amorites", "Gilead", "Horeb", "Heshbon", "Levite", "Isaac", "Arnon", "Manasseh", "Israelite", "Arabah", "Reuben", "Pisgah"],
    6: ["Jordan", "Manasseh", "Jericho", "Reuben", "Ephraim", "Gilead", "Amorites", "Hebron", "Bashan", "Gibeon", "Gilgal", "Canaanites", "Debir", "Caleb", "Lachish"],
    7: ["Gideon", "Samson", "Abimelech", "Benjamin", "Shechem", "Jephthah", "Gilead", "Ephraim", "Gibeah", "Micah", "Sisera", "Midian", "Manoah", "Canaanites", "Ammonites"],
    8: ["Naomi", "Bethlehem", "Elimelech", "Mahlon", "Jesse", "Moabitess", "Perez", "Moabite", "Chilion", "Orpah", "Hezron", "Salmon", "Nahshon", "Amminadab", "Rachel"],
    9: ["Samuel", "Jonathan", "Philistine", "Jesse", "Nabal", "Achish", "Hannah", "Ramah", "Keilah", "Gilgal", "Abner", "Amalekites", "Benjamin", "Ahimelech", "Gibeah"],
    10: ["Absalom", "Abner", "Amnon", "Jonathan", "Hebron", "Uriah", "Ahithophel", "Jordan", "Mephibosheth", "Abishai", "Tamar", "Zadok", "Nathan", "Zeruiah", "Asahel"],
    11: ["Jeroboam", "Elijah", "Jehoshaphat", "Adonijah", "Baasha", "Rehoboam", "Hiram", "Naboth", "Samaria", "Benaiah", "Ben-hadad", "Ahijah", "Jezebel", "Nathan", "Shimei"],
    12: ["Elisha", "Samaria", "Hezekiah", "Assyria", "Elijah", "Jeroboam", "Ahaziah", "Joram", "Joash", "Hazael", "Josiah", "Jehoash", "Gehazi", "Amaziah", "Jehoahaz"],
    13: ["Manasseh", "Hebron", "Merari", "Asaph", "Zadok", "Eleazar", "Shimei", "Benaiah", "Benjamin", "Heman", "Gilead", "Kohath", "Zechariah", "Azariah", "Shemaiah"],
    14: ["Hezekiah", "Jehoshaphat", "Rehoboam", "Jehoiada", "Manasseh", "Amaziah", "Josiah", "Jeroboam", "Ahaziah", "Joash", "Jehoram", "Abijah", "Uzziah", "Ephraim", "Benjamin"],
    15: ["Cyrus", "Persia", "Artaxerxes", "Jeshua", "Darius", "Zerubbabel", "Zechariah", "Rehum", "Nebuchadnezzar", "Euphrates", "Shallum", "Benjamin", "Harim", "Sheshbazzar", "Eliezer"],
    16: ["Jeshua", "Tobiah", "Meshullam", "Eliashib", "Sanballat", "Shemaiah", "Maaseiah", "Nehemiah", "Zechariah", "Jedaiah", "Hananiah", "Mattaniah", "Asaph", "Hanan", "Harim"],
    17: ["Mordecai", "Haman", "Esther", "Ahasuerus", "Xerxes", "Vashti", "Shushan", "Purim", "Hammedatha", "Hathach", "Agagite", "Persia", "Media", "Hegai", "Zeresh"],
    18: ["Satan", "Elihu", "Eliphaz", "Bildad", "Temanite", "Zophar", "Shuhite", "Sheol", "Naamathite", "Orion", "Pleiades", "Buzite", "Ophir", "Rahab", "Barachel"],
    19: ["Selah", "Hallelujah", "Sheol", "Asaph", "Korah", "Bashan", "Lebanon", "Ephraim", "Philistia", "Canaan", "Jordan", "Hermon", "Manasseh", "Meribah", "Interlude"],
    20: ["Sheol", "Lemuel", "Hezekiah", "Ithiel", "Jakeh", "Abaddon", "God-loyal", "Massa", "Madame", "Creator", "Egyptian", "Hades", "Rephaim", "God-honoring", "God-knowledge"],
    21: ["Creator", "Sheol", "Quester", "God-fearing", "God-given"],
    22: ["Lebanon", "Gilead", "Shulammite", "Tirzah", "Sharon", "Kedar", "Damascus", "Heshbon", "Hermon", "Carmel", "Amana", "Senir", "Baal-hamon", "Bath-rabbim", "Shulamite"],
    23: ["Assyria", "Hezekiah", "Isaiah", "Ephraim", "Egyptians", "Lebanon", "Samaria", "Damascus", "Tarshish", "Assyrian", "Shebna", "Eliakim", "Assyrians", "Sheol", "Rezin"],
    24: ["Jeremiah", "Zedekiah", "Nebuchadnezzar", "Chaldeans", "Baruch", "Jehoiakim", "Gedaliah", "Ishmael", "Josiah", "Johanan", "Ahikam", "Mizpah", "Babylonia", "Nethaniah", "Nebuzaradan"],
    25: ["Sodom", "Assyria", "Egyptians", "Assyrians", "Gomorrah", "Nazarites", "Asshur", "Zedekiah", "Judean", "Babylonians", "God-given"],
    26: ["Egyptians", "Samaria", "Sodom", "Ezekiel", "Oholibah", "Chebar", "Damascus", "Lebanon", "Hamath", "Tubal", "Nebuchadnezzar", "Meshech", "Oholah", "Assyrians", "Benjamin"],
    27: ["Daniel", "Nebuchadnezzar", "Meshach", "Shadrach", "Abednego", "Belteshazzar", "Darius", "Belshazzar", "Persia", "Chaldeans", "Mishael", "Hananiah", "Azariah", "Arioch", "Medes"],
    28: ["Ephraim", "Assyria", "Samaria", "Jezreel", "Gibeah", "Hosea", "Gilgal", "Lebanon", "Gomer", "Bethel", "Gilead", "Beth-aven", "Baals", "Lo-Ruhamah", "Admah"],
    29: ["Jehoshaphat", "Pethuel", "Sidon", "Philistia", "Greeks", "Sabeans", "Mediterranean", "Sheba", "Grecians", "Zidon", "Judean", "Palestine", "Jehosh", "Javan", "Arabia"],
    30: ["Bethel", "Samaria", "Jeroboam", "Damascus", "Gilgal", "Amaziah", "Gilead", "Carmel", "Isaac", "Ashdod", "Hamath", "Beersheba", "Amorite", "Rabbah", "Sodom"],
    31: ["Gilead", "Teman", "Benjamin", "Ephraim", "Samaria", "Zarephath", "Obadiah", "Sepharad", "Negev", "Canaanites", "Negeb", "Philistine", "Philistia", "Shephelah", "Canaan"],
    32: ["Jonah", "Nineveh", "Tarshish", "Joppa", "Hebrew", "Amittai", "Sheol", "Spain", "Mediterranean", "Ninevites"],
    33: ["Samaria", "Assyria", "Micah", "Balak", "Gilead", "Miriam", "Bashan", "Balaam", "Gilgal", "Jotham", "Moresheth", "Hezekiah", "Assyrian", "Bethlehem", "Lachish"],
    34: ["Nineveh", "Assyria", "Nahum", "Bashan", "Lebanon", "Carmel", "Thebes", "Ethiopia", "Elkosh", "Libya", "Elkoshite", "Assyrian", "Lubim", "Assyrians", "No-amon"],
    35: ["Selah", "Habakkuk", "Babylonians", "Cushan", "Paran", "Midian", "Lebanon", "Chaldeans", "Teman", "Sheol", "Babylonian", "Chaldean", "Babylonia", "World-conquering", "Sinai"],
    36: ["Ashkelon", "Ammon", "Canaan", "Nineveh", "Zephaniah", "Gedaliah", "Cushi", "Sodom", "Ashdod", "Assyria", "Gomorrah", "Ekron", "Josiah", "Amariah", "Hezekiah"],
    37: ["Haggai", "Zerubbabel", "Shealtiel", "Jehozadak", "Darius", "Josedech", "Jeshua", "Persia", "Jozadak", "December", "October", "Babylonia", "September"],
    38: ["Zechariah", "Zerubbabel", "Darius", "Satan", "Ephraim", "Ekron", "Lebanon", "Ashkelon", "Jedaiah", "Assyria", "Zephaniah", "Tobijah", "Berechiah", "Heldai", "Josiah"],
    39: ["Elijah", "Malachi", "Horeb", "Sinai", "Edomites", "Levite", "GOD-cursed", "GOD-fearers"],
    40: ["Pharisees", "Peter", "Galilee", "Herod", "Pilate", "Simon", "Elijah", "Judas", "Messiah", "Judea", "Sadducees", "James", "Baptist", "Isaiah", "Jordan"],
    41: ["Peter", "James", "Galilee", "Pharisees", "Pilate", "Simon", "Herod", "Elijah", "Satan", "Judas", "Jordan", "Andrew", "Bethany", "Zebedee", "Magdalene"],
    42: ["Peter", "Pharisees", "Simon", "Galilee", "Herod", "Pilate", "Judea", "Elizabeth", "James", "Nazareth", "Pharisee", "Messiah", "Elijah", "Zechariah", "Satan"],
    43: ["Peter", "Simon", "Pilate", "Pharisees", "Galilee", "Lazarus", "Jewish", "Philip", "Judas", "Messiah", "Martha", "Thomas", "Rabbi", "Judea", "Nathanael"],
    44: ["Peter", "Barnabas", "Antioch", "Jewish", "Philip", "Silas", "Caesarea", "Festus", "Simon", "Damascus", "Agrippa", "Judea", "Ananias", "Stephen", "Herod"],
    45: ["Isaiah", "Jewish", "Greek", "Messiah", "Isaac", "Spain", "Sarah", "Greeks", "Christians", "Elijah", "Achaia", "Tertius", "Benjamin", "Israelite", "Hosea"],
    46: ["Apollos", "Greeks", "Stephanas", "Christian", "Cephas", "Timothy", "Ephesus", "Satan", "Macedonia", "Peter", "Messiah", "Christians", "Corinth", "Barnabas", "Crispus"],
    47: ["Titus", "Macedonia", "Satan", "Corinth", "Achaia", "Timothy", "Damascus", "Messiah", "Troas", "Hebrews", "Judea", "Aretas", "Macedonians", "Corinthians", "Christians"],
    48: ["Peter", "Jewish", "James", "Barnabas", "Cephas", "Sinai", "Titus", "Arabia", "Hagar", "Greek", "Messiah", "Isaac", "Antioch", "Galatia", "Damascus"],
    49: ["Messiah", "Tychicus", "Ephesus", "Jewish", "Christians", "Christian", "Satan", "Creator", "God-fashioned", "Genesis", "Deuteronomy"],
    50: ["Timothy", "Epaphroditus", "Philippi", "Benjamin", "Clement", "Thessalonica", "Syntyche", "Macedonia", "Hebrew", "Philippians", "Caesar", "Pharisee", "Euodia", "Hebrews", "Christians"],
    51: ["Laodicea", "Epaphras", "Onesimus", "Tychicus", "Justus", "Barnabas", "Demas", "Aristarchus", "Hierapolis", "Archippus", "Timothy", "Greek", "Colossae", "Messiah", "Nympha"],
    52: ["Timothy", "Macedonia", "Achaia", "Satan", "Philippi", "Athens", "Judea", "Thessalonians", "Silvanus", "Silas", "Christians", "Thessalonica", "Greece", "Messiah", "Timotheus"],
    53: ["Satan", "Timothy", "Thessalonians", "Silvanus", "Silas", "Anarchist", "Messiah", "Thessalonica", "Thessalonian", "Christians", "Timotheus", "Christian"],
    54: ["Timothy", "Satan", "Alexander", "Pilate", "Pontius", "Ephesus", "Macedonia", "Hymenaeus", "Christian", "Christians", "Messiah", "Timotheus", "God-Alive", "Priest-Mediator", "Jesus-faith"],
    55: ["Onesiphorus", "Ephesus", "Timothy", "Jambres", "Jannes", "Alexander", "Antioch", "Lystra", "Galatia", "Corinth", "Titus", "Demas", "Eunice", "Crescens", "Dalmatia"],
    56: ["Crete", "Jewish", "Titus", "Artemas", "Zenas", "Apollos", "Tychicus", "Nicopolis", "Cretans", "Judaism", "Messiah", "Christians", "Christian", "God-honoring", "God-filled"],
    57: ["Onesimus", "Philemon", "Demas", "Timothy", "Aristarchus", "Epaphras", "Archippus", "Apphia", "Messiah", "Christian", "Marcus", "Christians", "Timotheus"],
    58: ["Melchizedek", "Isaac", "Salem", "Enoch", "Messiah", "Jericho", "Egyptians", "Samuel", "Barak", "Samson", "Rahab", "Jephthah", "Timothy", "Sarah", "Gideon"],
    59: ["Isaac", "Rahab", "Elijah", "James", "Christian", "Sabaoth", "Christians", "Creator", "Jericho", "Jewish", "Deuteronomy", "Christ-originated", "God-talk", "God-acts", "Israelite"],
    60: ["Christian", "Sarah", "Peter", "Pontus", "Galatia", "Cappadocia", "Bithynia", "Creator", "Silvanus", "Messiah", "Silas", "Christians", "Isaiah", "God-ignorant", "Christ-approved"],
    61: ["Balaam", "Sodom", "Peter", "Gomorrah", "Simon", "Simeon", "Christian", "Bosor", "Messiah", "Tartarus", "Bezer", "Matthew", "Gomorrha"],
    62: ["Messiah", "Christian", "Satan", "God-begotten", "Christians", "God-protected", "Priest-Friend", "Christ-denying"],
    63: ["Cyria", "Godspeed", "Messiah", "Christians"],
    64: ["Demetrius", "Diotrephes", "Gaius", "Christians", "Christian"],
    65: ["Michael", "Korah", "Enoch", "Sodom", "Balaam", "James", "Gomorrah", "Messiah", "Satan", "Christians", "Christian", "Judas", "Gomorrha"],
    66: ["Satan", "Sardis", "Thyatira", "Hallelujah", "Alpha", "Omega", "Hades", "Hebrew", "Philadelphia", "Ephesus", "Smyrna", "Euphrates", "Nicolaitans", "Laodicea", "Pergamum"]
}
